import { db, schema } from './index';
import { sql } from 'drizzle-orm';
import { seedAllArpitBlogs } from './fetch-and-seed-blogs';
import { seedAllWritings } from './seed-all-writings';
import { seedAllPapers } from './seed-all-papers';
import { seedMediaAndGalleries } from './seed-media-and-galleries';
import { seedHobbies } from './seed-hobbies';

export async function seedDatabase() {
  console.log('🌱 Starting database seed...');
  const now = Date.now();

  // 1. Profile, Education, Experience, Media & Galleries (Scanned from public assets & resume)
  await seedMediaAndGalleries();

  // 4a. GitHub Repo Snapshots
  const githubSnapshots = [
    {
      id: 'Ashutosh-Repos/Tessera',
      name: 'Tessera',
      fullName: 'Ashutosh-Repos/Tessera',
      description: 'Multi-Region Distributed Video Transcoding & HLS/DASH Packaging Engine in Go (Consistent Hash Ring, S3 Ingress, NATS, Redis Sharding)',
      stars: 24,
      forks: 3,
      openIssues: 0,
      primaryLanguage: 'Go',
      languagesJson: JSON.stringify({ Go: 94.2, Shell: 5.8 }),
      latestCommitSha: 'a8b7c6d',
      latestCommitAt: now - 86400000 * 12,
      isPinned: true,
      repoUrl: 'https://github.com/Ashutosh-Repos/Tessera',
      homepageUrl: null,
      topicsJson: JSON.stringify(['distributed-systems', 'transcoding', 'golang', 'hls', 'nats']),
      syncedAt: now,
    },
    {
      id: 'Ashutosh-Repos/cheating-daddy',
      name: 'cheating-daddy',
      fullName: 'Ashutosh-Repos/cheating-daddy',
      description: 'AI-assisted developer interview & practice accelerator with live multimodal assistance',
      stars: 18,
      forks: 2,
      openIssues: 0,
      primaryLanguage: 'TypeScript',
      languagesJson: JSON.stringify({ TypeScript: 82.5, CSS: 12.0, HTML: 5.5 }),
      latestCommitSha: 'f1e2d3c',
      latestCommitAt: now - 86400000 * 5,
      isPinned: true,
      repoUrl: 'https://github.com/Ashutosh-Repos/cheating-daddy',
      homepageUrl: 'https://cheatingdaddy.com/',
      topicsJson: JSON.stringify(['ai', 'nextjs', 'react', 'developer-tools']),
      syncedAt: now,
    },
    {
      id: 'Ashutosh-Repos/portfolio_v2',
      name: 'portfolio_v2',
      fullName: 'Ashutosh-Repos/portfolio_v2',
      description: 'Ultra-modern portfolio with custom liquid glass physics & backend data platform',
      stars: 14,
      forks: 1,
      openIssues: 0,
      primaryLanguage: 'TypeScript',
      languagesJson: JSON.stringify({ TypeScript: 89.0, CSS: 9.5, Other: 1.5 }),
      latestCommitSha: '9c8b7a6',
      latestCommitAt: now - 86400000 * 2,
      isPinned: true,
      repoUrl: 'https://github.com/Ashutosh-Repos/portfolio_v2',
      homepageUrl: 'https://portfolio-3-0-blond.vercel.app',
      topicsJson: JSON.stringify(['portfolio', 'nextjs', 'liquid-glass', 'drizzle']),
      syncedAt: now,
    },
    {
      id: 'Ashutosh-Repos/Chatify',
      name: 'Chatify',
      fullName: 'Ashutosh-Repos/Chatify',
      description: 'Realtime chat platform using WebSockets, Next.js, Prisma, PostgreSQL, & Zustand',
      stars: 12,
      forks: 2,
      openIssues: 0,
      primaryLanguage: 'TypeScript',
      languagesJson: JSON.stringify({ TypeScript: 85.0, JavaScript: 10.0, CSS: 5.0 }),
      latestCommitSha: '4d5e6f7',
      latestCommitAt: now - 86400000 * 45,
      isPinned: false,
      repoUrl: 'https://github.com/Ashutosh-Repos/Chatify',
      homepageUrl: null,
      topicsJson: JSON.stringify(['websockets', 'nextjs', 'prisma', 'chat']),
      syncedAt: now,
    },
    {
      id: 'Ashutosh-Repos/Bunly',
      name: 'Bunly',
      fullName: 'Ashutosh-Repos/Bunly',
      description: 'High-performance, feature-rich Video-On-Demand (VOD) streaming platform',
      stars: 9,
      forks: 1,
      openIssues: 0,
      primaryLanguage: 'TypeScript',
      languagesJson: JSON.stringify({ TypeScript: 88.0, HTML: 6.0, CSS: 6.0 }),
      latestCommitSha: '3a2b1c0',
      latestCommitAt: now - 86400000 * 60,
      isPinned: true,
      repoUrl: 'https://github.com/Ashutosh-Repos/Bunly',
      homepageUrl: null,
      topicsJson: JSON.stringify(['video-on-demand', 'streaming', 'hls']),
      syncedAt: now,
    },
    {
      id: 'Ashutosh-Repos/video-encoder',
      name: 'video-encoder',
      fullName: 'Ashutosh-Repos/video-encoder',
      description: 'Multithreaded video processing engine with Next.js, FFmpeg & HLS streaming',
      stars: 7,
      forks: 1,
      openIssues: 0,
      primaryLanguage: 'TypeScript',
      languagesJson: JSON.stringify({ TypeScript: 78.0, JavaScript: 15.0, Shell: 7.0 }),
      latestCommitSha: '7f8e9d0',
      latestCommitAt: now - 86400000 * 90,
      isPinned: true,
      repoUrl: 'https://github.com/Ashutosh-Repos/video-encoder',
      homepageUrl: null,
      topicsJson: JSON.stringify(['ffmpeg', 'video-processing', 'hls']),
      syncedAt: now,
    },
    {
      id: 'Ashutosh-Repos/ShellGreets',
      name: 'ShellGreets',
      fullName: 'Ashutosh-Repos/ShellGreets',
      description: 'Smart, motivational greeting theme for terminal with dynamic day progress bar',
      stars: 15,
      forks: 4,
      openIssues: 0,
      primaryLanguage: 'Shell',
      languagesJson: JSON.stringify({ Shell: 100.0 }),
      latestCommitSha: '1a2b3c4',
      latestCommitAt: now - 86400000 * 75,
      isPinned: false,
      repoUrl: 'https://github.com/Ashutosh-Repos/ShellGreets',
      homepageUrl: null,
      topicsJson: JSON.stringify(['zsh', 'bash', 'terminal', 'developer-tools']),
      syncedAt: now,
    },
    {
      id: 'Ashutosh-Repos/Post',
      name: 'Post',
      fullName: 'Ashutosh-Repos/Post',
      description: 'Minimalist social media platform built for sharing thoughts and updates',
      stars: 5,
      forks: 0,
      openIssues: 0,
      primaryLanguage: 'TypeScript',
      languagesJson: JSON.stringify({ TypeScript: 84.0, CSS: 16.0 }),
      latestCommitSha: '5e6f7a8',
      latestCommitAt: now - 86400000 * 110,
      isPinned: true,
      repoUrl: 'https://github.com/Ashutosh-Repos/Post',
      homepageUrl: null,
      topicsJson: JSON.stringify(['social-app', 'nextjs', 'prisma']),
      syncedAt: now,
    },
    {
      id: 'Ashutosh-Repos/Finance-Dashboard-UI',
      name: 'Finance-Dashboard-UI',
      fullName: 'Ashutosh-Repos/Finance-Dashboard-UI',
      description: 'Modern financial analytics dashboard UI with data visualization',
      stars: 11,
      forks: 2,
      openIssues: 0,
      primaryLanguage: 'TypeScript',
      languagesJson: JSON.stringify({ TypeScript: 80.0, CSS: 20.0 }),
      latestCommitSha: '8d9e0f1',
      latestCommitAt: now - 86400000 * 130,
      isPinned: false,
      repoUrl: 'https://github.com/Ashutosh-Repos/Finance-Dashboard-UI',
      homepageUrl: null,
      topicsJson: JSON.stringify(['finance', 'dashboard', 'charts']),
      syncedAt: now,
    },
    {
      id: 'Ashutosh-Repos/macbook-usb-tethering',
      name: 'macbook-usb-tethering',
      fullName: 'Ashutosh-Repos/macbook-usb-tethering',
      description: 'USB tethering driver & kernel extension utility for macOS',
      stars: 19,
      forks: 3,
      openIssues: 0,
      primaryLanguage: 'C',
      languagesJson: JSON.stringify({ C: 92.0, Makefile: 8.0 }),
      latestCommitSha: '2b3c4d5',
      latestCommitAt: now - 86400000 * 150,
      isPinned: true,
      repoUrl: 'https://github.com/Ashutosh-Repos/macbook-usb-tethering',
      homepageUrl: null,
      topicsJson: JSON.stringify(['macos', 'kernel-extension', 'c', 'driver']),
      syncedAt: now,
    },
    {
      id: 'Ashutosh-Repos/VidtubeBackend',
      name: 'VidtubeBackend',
      fullName: 'Ashutosh-Repos/VidtubeBackend',
      description: 'Scalable video platform backend architecture with Node.js & MongoDB',
      stars: 6,
      forks: 1,
      openIssues: 0,
      primaryLanguage: 'JavaScript',
      languagesJson: JSON.stringify({ JavaScript: 95.0, Shell: 5.0 }),
      latestCommitSha: '6c7d8e9',
      latestCommitAt: now - 86400000 * 180,
      isPinned: false,
      repoUrl: 'https://github.com/Ashutosh-Repos/VidtubeBackend',
      homepageUrl: null,
      topicsJson: JSON.stringify(['nodejs', 'mongodb', 'express', 'video']),
      syncedAt: now,
    },
    {
      id: 'Ashutosh-Repos/hls-server',
      name: 'hls-server',
      fullName: 'Ashutosh-Repos/hls-server',
      description: 'Lightweight HTTP Live Streaming (HLS) server for video distribution',
      stars: 8,
      forks: 1,
      openIssues: 0,
      primaryLanguage: 'Go',
      languagesJson: JSON.stringify({ Go: 96.0, Shell: 4.0 }),
      latestCommitSha: '9e0f1a2',
      latestCommitAt: now - 86400000 * 200,
      isPinned: false,
      repoUrl: 'https://github.com/Ashutosh-Repos/hls-server',
      homepageUrl: null,
      topicsJson: JSON.stringify(['golang', 'hls', 'streaming', 'http']),
      syncedAt: now,
    },
    {
      id: 'Ashutosh-Repos/ShAI',
      name: 'ShAI',
      fullName: 'Ashutosh-Repos/ShAI',
      description: 'AI-Powered CLI Assistant translating natural language into safe shell commands (Ink, React, SQLite, Ollama, Claude, OpenAI)',
      stars: 22,
      forks: 3,
      openIssues: 0,
      primaryLanguage: 'TypeScript',
      languagesJson: JSON.stringify({ TypeScript: 92.0, JavaScript: 5.0, Shell: 3.0 }),
      latestCommitSha: 'b4c5d6e',
      latestCommitAt: now - 86400000 * 8,
      isPinned: true,
      repoUrl: 'https://github.com/Ashutosh-Repos/ShAI',
      homepageUrl: 'https://www.npmjs.com/package/shai-shell',
      topicsJson: JSON.stringify(['cli', 'ai', 'developer-tools', 'typescript', 'terminal']),
      syncedAt: now,
    },
  ];

  await db
    .insert(schema.githubRepoSnapshot)
    .values(githubSnapshots)
    .onConflictDoUpdate({
      target: schema.githubRepoSnapshot.id,
      set: {
        stars: sql`excluded.stars`,
        forks: sql`excluded.forks`,
        description: sql`excluded.description`,
        syncedAt: now,
      },
    });

  // 4b. Projects (Linked to GitHub Snapshots)
  const projectsData = [
    {
      id: 'proj-shai',
      slug: 'shai-cli',
      title: 'Shai — AI Powered CLI Assistant',
      tagline: 'Translates devs natural language commands into safe, executable shell commands',
      description: 'A modular command-line utility translating natural language into shell commands with interactive terminal UI, security interceptors, multi-LLM routing, and encrypted offline history.',
      caseStudyMarkdown: '# Shai — AI Powered CLI Assistant\n\nA production command-line developer assistant published on npm, combining React/Ink interactive terminal UI with security validation and unified multi-LLM clients.',
      status: 'active',
      featuredPriority: 1,
      demoUrl: 'https://www.npmjs.com/package/shai-shell',
      packageUrl: 'https://www.npmjs.com/package/shai-shell',
      githubRepoId: 'Ashutosh-Repos/ShAI',
      overrideGithubData: true,
      technologiesJson: JSON.stringify(['TypeScript', 'Node.js', 'React', 'Ink', 'SQLite', 'Claude', 'OpenAI', 'Gemini']),
      architectureJson: JSON.stringify([
        'Modular OOP design pattern separating configuration, SQLite managers, and LLM API clients',
        'Interactive TUI using React and Ink rendering real-time asynchronous streaming token flows',
        'Automated security validation module parsing shell AST to intercept destructive commands',
        'Encrypted offline prompt history engine leveraging embedded local SQLite'
      ]),
      lessonsLearnedMarkdown: 'Building terminal interfaces with React Ink requires strict layout lifecycle discipline, atomic state updates, and graceful terminal resize event debouncing.',
      coverImageUrl: null,
      sortOrder: 1,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'proj-cheating-daddy',
      slug: 'cheating-daddy',
      title: 'Cheating Daddy',
      tagline: 'AI-assisted developer interview & practice accelerator',
      description: 'An open-source developer utility designed for intelligent coding interviews and live technical problem solving with multimodal AI assistants.',
      caseStudyMarkdown: '# Cheating Daddy\n\nA full breakdown of the real-time AI architecture, client-side hooks, and latency optimization techniques used.',
      status: 'active',
      featuredPriority: 2,
      demoUrl: 'https://cheatingdaddy.com/',
      packageUrl: null,
      githubRepoId: 'Ashutosh-Repos/cheating-daddy',
      overrideGithubData: false,
      technologiesJson: JSON.stringify(['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'OpenAI API']),
      architectureJson: JSON.stringify(['Next.js App Router', 'Edge Streaming', 'Framer Motion']),
      lessonsLearnedMarkdown: 'Streaming responses directly from Edge runtimes radically improves perceived performance.',
      coverImageUrl: '/images/cheatingdaddysq.png',
      sortOrder: 1,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'proj-portfolio-v2',
      slug: 'portfolio-v2',
      title: 'Liquid Glass Portfolio & Data Backbone',
      tagline: 'Ultra-modern portfolio with custom liquid glass physics & backend data platform',
      description: 'High-aesthetic personal website powered by custom liquid glass optics, Next.js 16, and an isolated personal-data API backbone.',
      caseStudyMarkdown: '# Portfolio Architecture\n\nModular monolith with SQLite/libSQL, zero-latency caching, and provider-independent external integrations.',
      status: 'active',
      featuredPriority: 2,
      demoUrl: 'https://portfolio-3-0-blond.vercel.app',
      packageUrl: null,
      githubRepoId: 'Ashutosh-Repos/portfolio_v2',
      overrideGithubData: false,
      technologiesJson: JSON.stringify(['Next.js 16', 'React 19', 'Drizzle ORM', 'libSQL', 'Tailwind CSS 4']),
      architectureJson: JSON.stringify(['Hexagonal Architecture', 'libSQL WAL Mode', 'Dynamic Blurhash Placeholders']),
      lessonsLearnedMarkdown: 'Separating external provider syncs from user HTTP requests eliminates rate limits and cascading latency.',
      coverImageUrl: '/images/anamigospic.jpeg',
      sortOrder: 2,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'proj-tessera',
      slug: 'tessera',
      title: 'Tessera',
      tagline: 'Distributed Video Transcoding & HLS/DASH Packaging Engine in Go',
      description: 'Multi-Region Distributed Video Transcoding & HLS/DASH Packaging Engine in Go (Consistent Hash Ring, S3 Ingress, NATS, Redis Sharding).',
      caseStudyMarkdown: '# Tessera Architecture\n\nHigh-throughput distributed transcoding engine built with Go, FFmpeg bindings, and NATS event streams.',
      status: 'active',
      featuredPriority: 3,
      demoUrl: null,
      packageUrl: null,
      githubRepoId: 'Ashutosh-Repos/Tessera',
      overrideGithubData: false,
      technologiesJson: JSON.stringify(['Go', 'FFmpeg', 'NATS', 'Redis', 'Docker']),
      architectureJson: JSON.stringify(['Consistent Hash Ring', 'S3 Ingress Pipeline']),
      lessonsLearnedMarkdown: null,
      coverImageUrl: null,
      sortOrder: 3,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'proj-chatify',
      slug: 'chatify',
      title: 'Chatify',
      tagline: 'Realtime chat platform using WebSockets, Next.js, Prisma, & Zustand',
      description: 'Realtime chat platform using WebSockets, Next.js, Prisma, PostgreSQL, & Zustand.',
      caseStudyMarkdown: null,
      status: 'completed',
      featuredPriority: 4,
      demoUrl: null,
      packageUrl: null,
      githubRepoId: 'Ashutosh-Repos/Chatify',
      overrideGithubData: false,
      technologiesJson: JSON.stringify(['Next.js', 'WebSockets', 'Prisma', 'PostgreSQL', 'Zustand']),
      architectureJson: JSON.stringify(['WebSocket Cluster', 'Optimistic UI Updates']),
      lessonsLearnedMarkdown: null,
      coverImageUrl: null,
      sortOrder: 4,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'proj-bunly',
      slug: 'bunly',
      title: 'Bunly',
      tagline: 'High-performance Video-On-Demand (VOD) streaming platform',
      description: 'High-performance, feature-rich Video-On-Demand (VOD) streaming platform with adaptive bitrate streaming.',
      caseStudyMarkdown: null,
      status: 'completed',
      featuredPriority: 5,
      demoUrl: null,
      packageUrl: null,
      githubRepoId: 'Ashutosh-Repos/Bunly',
      overrideGithubData: false,
      technologiesJson: JSON.stringify(['TypeScript', 'React', 'HLS.js', 'Node.js']),
      architectureJson: JSON.stringify(['Adaptive Bitrate Streaming']),
      lessonsLearnedMarkdown: null,
      coverImageUrl: null,
      sortOrder: 5,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'proj-video-encoder',
      slug: 'video-encoder',
      title: 'video-encoder',
      tagline: 'Multithreaded video processing engine with Next.js & FFmpeg',
      description: 'Multithreaded video processing engine with Next.js, FFmpeg & HLS streaming for rapid parallel video transcoding.',
      caseStudyMarkdown: null,
      status: 'completed',
      featuredPriority: 6,
      demoUrl: null,
      packageUrl: null,
      githubRepoId: 'Ashutosh-Repos/video-encoder',
      overrideGithubData: false,
      technologiesJson: JSON.stringify(['TypeScript', 'FFmpeg', 'Node.js', 'Next.js']),
      architectureJson: JSON.stringify(['Worker Threads', 'Pipeline Streaming']),
      lessonsLearnedMarkdown: null,
      coverImageUrl: null,
      sortOrder: 6,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'proj-shellgreets',
      slug: 'shellgreets',
      title: 'ShellGreets',
      tagline: 'Smart, motivational greeting theme for terminal with dynamic day progress bar',
      description: 'Smart, motivational greeting theme for terminal with dynamic day progress bar and personalized productivity metrics.',
      caseStudyMarkdown: null,
      status: 'completed',
      featuredPriority: 7,
      demoUrl: null,
      packageUrl: null,
      githubRepoId: 'Ashutosh-Repos/ShellGreets',
      overrideGithubData: false,
      technologiesJson: JSON.stringify(['Shell', 'Zsh', 'Bash']),
      architectureJson: JSON.stringify(['POSIX Compliant', 'ANSI Color Engine']),
      lessonsLearnedMarkdown: null,
      coverImageUrl: null,
      sortOrder: 7,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'proj-post',
      slug: 'post',
      title: 'Post',
      tagline: 'Minimalist social media platform built for sharing thoughts and updates',
      description: 'Minimalist social media platform built for sharing thoughts, media, and architectural thoughts.',
      caseStudyMarkdown: null,
      status: 'completed',
      featuredPriority: null,
      demoUrl: null,
      packageUrl: null,
      githubRepoId: 'Ashutosh-Repos/Post',
      overrideGithubData: false,
      technologiesJson: JSON.stringify(['TypeScript', 'React', 'Tailwind CSS']),
      architectureJson: JSON.stringify(['Server Components', 'Optimistic Mutations']),
      lessonsLearnedMarkdown: null,
      coverImageUrl: null,
      sortOrder: 8,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'proj-finance-dashboard',
      slug: 'finance-dashboard-ui',
      title: 'Finance-Dashboard-UI',
      tagline: 'Modern financial analytics dashboard UI with data visualization',
      description: 'Modern financial analytics dashboard UI with interactive charts, portfolio distribution, and ledger tracking.',
      caseStudyMarkdown: null,
      status: 'completed',
      featuredPriority: null,
      demoUrl: null,
      packageUrl: null,
      githubRepoId: 'Ashutosh-Repos/Finance-Dashboard-UI',
      overrideGithubData: false,
      technologiesJson: JSON.stringify(['TypeScript', 'Next.js', 'Chart.js']),
      architectureJson: JSON.stringify(['Responsive Glass Grids']),
      lessonsLearnedMarkdown: null,
      coverImageUrl: null,
      sortOrder: 9,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'proj-macbook-usb-tethering',
      slug: 'macbook-usb-tethering',
      title: 'macbook-usb-tethering',
      tagline: 'USB tethering driver & kernel extension utility for macOS',
      description: 'Low-level USB tethering driver and network interface utility crafted in C for high-throughput connectivity on macOS.',
      caseStudyMarkdown: null,
      status: 'completed',
      featuredPriority: null,
      demoUrl: null,
      packageUrl: null,
      githubRepoId: 'Ashutosh-Repos/macbook-usb-tethering',
      overrideGithubData: false,
      technologiesJson: JSON.stringify(['C', 'macOS Kernel', 'USB']),
      architectureJson: JSON.stringify(['Kernel Extension', 'IOKit Interface']),
      lessonsLearnedMarkdown: null,
      coverImageUrl: null,
      sortOrder: 10,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'proj-vidtubebackend',
      slug: 'vidtubebackend',
      title: 'VidtubeBackend',
      tagline: 'Scalable video platform backend architecture with Node.js & MongoDB',
      description: 'Scalable video platform backend architecture featuring user authentication, video transcode queues, and aggregation pipelines.',
      caseStudyMarkdown: null,
      status: 'completed',
      featuredPriority: null,
      demoUrl: null,
      packageUrl: null,
      githubRepoId: 'Ashutosh-Repos/VidtubeBackend',
      overrideGithubData: false,
      technologiesJson: JSON.stringify(['Node.js', 'Express', 'MongoDB', 'JWT']),
      architectureJson: JSON.stringify(['REST API', 'Aggregation Pipelines']),
      lessonsLearnedMarkdown: null,
      coverImageUrl: null,
      sortOrder: 11,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'proj-hls-server',
      slug: 'hls-server',
      title: 'hls-server',
      tagline: 'Lightweight HTTP Live Streaming (HLS) server for video distribution',
      description: 'Lightweight, concurrent HTTP Live Streaming (HLS) server built in Go for segment caching and byte-range delivery.',
      caseStudyMarkdown: null,
      status: 'completed',
      featuredPriority: null,
      demoUrl: null,
      packageUrl: null,
      githubRepoId: 'Ashutosh-Repos/hls-server',
      overrideGithubData: false,
      technologiesJson: JSON.stringify(['Go', 'HTTP/2', 'HLS']),
      architectureJson: JSON.stringify(['Zero-Copy File Serving']),
      lessonsLearnedMarkdown: null,
      coverImageUrl: null,
      sortOrder: 12,
      createdAt: now,
      updatedAt: now,
    },
  ];

  await db
    .insert(schema.project)
    .values(projectsData)
    .onConflictDoUpdate({
      target: schema.project.id,
      set: {
        title: sql`excluded.title`,
        tagline: sql`excluded.tagline`,
        description: sql`excluded.description`,
        githubRepoId: sql`excluded.github_repo_id`,
        demoUrl: sql`excluded.demo_url`,
        technologiesJson: sql`excluded.technologies_json`,
        architectureJson: sql`excluded.architecture_json`,
        featuredPriority: sql`excluded.featured_priority`,
        sortOrder: sql`excluded.sort_order`,
        updatedAt: now,
      },
    });

  // 5. Writings & Publications
  // 5a. Technical Blogs (36 Authentic Arpit Bhayani & Bloom Filters)
  await seedAllArpitBlogs();

  // 5b. Personal Essays (7 Authentic Designerdada Essays)
  await seedAllWritings();

  // 5c. Research Papershelf (82 Seminal Papers)
  await seedAllPapers();

  // 6. Skills
  const defaultSkills = [
    { name: 'TypeScript', slug: 'typescript', category: 'languages', tier: 'master', years: 4, icon: 'typescript', featured: true },
    { name: 'JavaScript', slug: 'javascript', category: 'languages', tier: 'master', years: 5, icon: 'javascript', featured: true },
    { name: 'Python', slug: 'python', category: 'languages', tier: 'proficient', years: 3, icon: 'python', featured: true },
    { name: 'Go', slug: 'go', category: 'languages', tier: 'familiar', years: 2, icon: 'go', featured: false },
    { name: 'React', slug: 'react', category: 'frameworks', tier: 'master', years: 4, icon: 'react', featured: true },
    { name: 'Next.js', slug: 'nextjs', category: 'frameworks', tier: 'master', years: 3, icon: 'nextjs', featured: true },
    { name: 'Tailwind CSS', slug: 'tailwindcss', category: 'frameworks', tier: 'master', years: 4, icon: 'tailwind', featured: true },
    { name: 'Node.js', slug: 'nodejs', category: 'frameworks', tier: 'master', years: 4, icon: 'nodejs', featured: true },
    { name: 'SQLite / libSQL', slug: 'sqlite', category: 'databases', tier: 'master', years: 3, icon: 'sqlite', featured: true },
    { name: 'PostgreSQL', slug: 'postgresql', category: 'databases', tier: 'proficient', years: 3, icon: 'postgresql', featured: true },
    { name: 'Docker', slug: 'docker', category: 'cloud_infra', tier: 'proficient', years: 2, icon: 'docker', featured: true },
    { name: 'Git & GitHub', slug: 'git', category: 'tools', tier: 'master', years: 5, icon: 'git', featured: true },
  ];

  for (let i = 0; i < defaultSkills.length; i++) {
    const s = defaultSkills[i];
    await db
      .insert(schema.skill)
      .values({
        id: `skill-${s.slug}`,
        slug: s.slug,
        name: s.name,
        category: s.category,
        proficiencyTier: s.tier,
        yearsOfExperience: s.years,
        iconSlug: s.icon,
        isFeatured: s.featured,
        sortOrder: i + 1,
      })
      .onConflictDoNothing();
  }

  // 7. Initial Integration Snapshots
  await db
    .insert(schema.externalActivitySnapshot)
    .values([
      {
        id: 'github_overview',
        provider: 'github',
        metricType: 'overview',
        payloadJson: JSON.stringify({
          user: {
            username: 'Ashutosh-Repos',
            name: 'Ashutosh',
            avatarUrl: 'https://avatars.githubusercontent.com/u/179326754?v=4',
            profileUrl: 'https://github.com/Ashutosh-Repos',
            followers: 1,
            publicRepos: 53,
          },
          impact: { stars: 2, forks: 0 },
          activity: { totalCommits: 250, mergedPRs: 15, closedIssues: 8, totalContributions: 320 },
          streak: { currentStreak: 12, longestStreak: 45 },
          languages: [
            { name: 'TypeScript', percentage: 48, color: '#3178c6', count: 48 },
            { name: 'JavaScript', percentage: 22, color: '#f7df1e', count: 22 },
            { name: 'Python', percentage: 16, color: '#3572a5', count: 16 },
            { name: 'HTML', percentage: 8, color: '#e34c26', count: 8 },
            { name: 'CSS', percentage: 6, color: '#563d7c', count: 6 },
          ],
        }),
        syncedAt: now,
      },
      {
        id: 'leetcode_overview',
        provider: 'leetcode',
        metricType: 'overview',
        payloadJson: JSON.stringify({
          user: {
            username: 'ashutosh0406',
            profileUrl: 'https://leetcode.com/u/ashutosh0406/',
            ranking: 1052423,
            avatarUrl: 'https://assets.leetcode.com/users/ashutosh0406/avatar_1783796482.png',
          },
          solved: { all: 164, easy: 47, medium: 97, hard: 20 },
          totalQuestions: { all: 3400, easy: 860, medium: 1800, hard: 840 },
          accuracy: { acceptanceRate: 81.2, totalSubmissions: 202, acceptedSubmissions: 164 },
          consistency: { streak: 3, totalActiveDays: 64 },
          topTags: [
            { name: 'Array', solved: 45 },
            { name: 'Hash Table', solved: 32 },
            { name: 'Dynamic Programming', solved: 28 },
            { name: 'String', solved: 24 },
            { name: 'Depth-First Search', solved: 20 },
          ],
        }),
        syncedAt: now,
      },
    ])
    .onConflictDoNothing();

  // 7. Hobbies, Movies & Webseries
  await seedHobbies();

  // 8. Schema Completeness: Achievements, Comprehensive Skills, Providers, Tags & Relations
  const { seedSchemaCompleteness } = await import('./seed-schema-completeness');
  await seedSchemaCompleteness();

  console.log('✅ Database seeded successfully!');
}

// Auto-run if invoked directly via tsx/node
if (require.main === module) {
  seedDatabase()
    .then(() => process.exit(0))
    .catch((err) => {
      console.error('❌ Seed failed:', err);
      process.exit(1);
    });
}
