import { db, schema } from './index';

export async function seedHobbies() {
  console.log(
    '🎬 Seeding full verified catalog of movies and web series (132 entries)...',
  );
  const now = Date.now();

  const entries = [
    {
      id: 'movie-ant-man',
      slug: 'ant-man',
      type: 'movie',
      title: 'Ant-Man',
      releaseYear: 2015,
      genresJson: '["Action","Comedy","Sci-Fi"]',
      creatorsJson: '["Peyton Reed","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/rQRnQfUl3kfp78nCWq8Ks04vnq1.jpg',
      myRating: 8.7,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'Clever micro-scale heist comedy. Thomas the Tank Engine toy train fight in Cassie room was inspired visual humor.',
    },
    {
      id: 'movie-ant-man-and-the-wasp',
      slug: 'ant-man-and-the-wasp',
      type: 'movie',
      title: 'Ant-Man and the Wasp',
      releaseYear: 2018,
      genresJson: '["Action","Comedy","Sci-Fi"]',
      creatorsJson: '["Peyton Reed","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/cFQEO687n1K6umXbInzocxcnAQz.jpg',
      myRating: 8.5,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'Breezy palate cleanser after Infinity War with inventive kitchen shrinking fight and the ominous post-credits dust scene.',
    },
    {
      id: 'movie-ant-man-and-the-wasp-quantumania',
      slug: 'ant-man-and-the-wasp-quantumania',
      type: 'movie',
      title: 'Ant-Man and the Wasp: Quantumania',
      releaseYear: 2023,
      genresJson: '["Action","Adventure","Sci-Fi"]',
      creatorsJson: '["Peyton Reed","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/qnqGbB22YJ7dSs4o6M7exTpNxPz.jpg',
      myRating: 8.4,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'Psychedelic Quantum Realm creatures and Jonathan Majors menacing debut as Kang the Conqueror.',
    },
    {
      id: 'movie-aquaman',
      slug: 'aquaman',
      type: 'movie',
      title: 'Aquaman',
      releaseYear: 2018,
      genresJson: '["Action","Adventure","Fantasy"]',
      creatorsJson: '["James Wan"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/ufl63EFcc5XpByEV2Ecdw6WJZAI.jpg',
      myRating: 9.0,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'James Wan unbridled visual imagination. The flare descent into The Trench and the Ring of Fire duel were visual feasts.',
    },
    {
      id: 'movie-aquaman-and-the-lost-kingdom',
      slug: 'aquaman-and-the-lost-kingdom',
      type: 'movie',
      title: 'Aquaman and the Lost Kingdom',
      releaseYear: 2023,
      genresJson: '["Action","Adventure","Fantasy"]',
      creatorsJson: '["James Wan"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/7lTnXOy0iNtBAdRP3TZvaKJ77F6.jpg',
      myRating: 8.4,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'Arthur and Orm buddy comedy adventure across the volcanic Necrus kingdom closing out the DCEU era.',
    },
    {
      id: 'movie-avengers-age-of-ultron',
      slug: 'avengers-age-of-ultron',
      type: 'movie',
      title: 'Avengers: Age of Ultron',
      releaseYear: 2015,
      genresJson: '["Action","Sci-Fi","Superhero"]',
      creatorsJson: '["Joss Whedon","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/btWdEP8M172ceW8RH4SH2XFvEab.jpg',
      myRating: 8.9,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'James Spader chilling philosophical voice for Ultron, the Hulkbuster brawl in Johannesburg, and Vision birth.',
    },
    {
      id: 'movie-avengers-endgame',
      slug: 'avengers-endgame',
      type: 'movie',
      title: 'Avengers: Endgame',
      releaseYear: 2019,
      genresJson: '["Action","Sci-Fi","Drama"]',
      creatorsJson: '["Anthony Russo","Joe Russo","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg',
      myRating: 9.7,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'Portals scene and Cap lifting Mjolnir. A once-in-a-generation theatrical spectacle closing 11 years of storytelling.',
    },
    {
      id: 'movie-avengers-infinity-war',
      slug: 'avengers-infinity-war',
      type: 'movie',
      title: 'Avengers: Infinity War',
      releaseYear: 2018,
      genresJson: '["Action","Sci-Fi","Adventure"]',
      creatorsJson: '["Anthony Russo","Joe Russo","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg',
      myRating: 9.8,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'A masterclass in pacing. Thanos is the protagonist of this relentless cosmic heist film. The ending snap silence was unforgettable.',
    },
    {
      id: 'movie-baahubali-2-the-conclusion',
      slug: 'baahubali-2-the-conclusion',
      type: 'movie',
      title: 'Baahubali 2: The Conclusion',
      releaseYear: 2017,
      genresJson: '["Action","Drama","Epic","War"]',
      creatorsJson: '["S.S. Rajamouli"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/sXf30F2HFpsFPXlNz7jpOySSV9I.jpg',
      myRating: 9.6,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'The coronation oath scene, the swan boat voyage, and solving the decade-defining question: Why Kattappa killed Baahubali.',
    },
    {
      id: 'movie-baahubali-the-beginning',
      slug: 'baahubali-the-beginning',
      type: 'movie',
      title: 'Baahubali: The Beginning',
      releaseYear: 2015,
      genresJson: '["Action","Drama","Epic","War"]',
      creatorsJson: '["S.S. Rajamouli"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/9BAjt8nSSms62uOVYn1t3C3dVto.jpg',
      myRating: 9.5,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'The giant waterfall climb, the avalanche sequence, and the colossal battle of Mahishmati. S.S. Rajamouli redefined Indian cinematic scale forever.',
    },
    {
      id: 'movie-batman-1989',
      slug: 'batman-1989',
      type: 'movie',
      title: 'Batman',
      releaseYear: 1989,
      genresJson: '["Action","Crime","Superhero"]',
      creatorsJson: '["Tim Burton","DC Comics","Warner Bros."]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/cij4dd21v2Rk2YtUQbV5kW69WB2.jpg',
      myRating: 9.2,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Tim Burton gothic German Expressionist Gotham City, Michael Keaton brooding Dark Knight, Jack Nicholson gleefully psychotic Joker, and Danny Elfman legendary brass theme.',
    },
    {
      id: 'movie-batman-begins',
      slug: 'batman-begins',
      type: 'movie',
      title: 'Batman Begins',
      releaseYear: 2005,
      genresJson: '["Action","Crime","Drama"]',
      creatorsJson: '["Christopher Nolan"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/sPX89Td70IDDjVr85jdSBb4rWGr.jpg',
      myRating: 9.3,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Grounded tactical reinvention of the Dark Knight mythos. The Himalayan League of Shadows training and fear gas climax set the standard.',
    },
    {
      id: 'movie-batman-returns',
      slug: 'batman-returns-1992',
      type: 'movie',
      title: 'Batman Returns',
      releaseYear: 1992,
      genresJson: '["Action","Crime","Fantasy"]',
      creatorsJson: '["Tim Burton","DC Comics","Warner Bros."]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/jKBjeXM7iBBV9UkUcOXx3m7FSHY.jpg',
      myRating: 9.1,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Burton pure auteur fairytale horror. Michelle Pfeiffer stitched-leather Catwoman remains the definitive standard, alongside Danny DeVito grotesque, tragic Penguin in snowy Gotham.',
    },
    {
      id: 'movie-batman-v-superman-dawn-of-justice',
      slug: 'batman-v-superman-dawn-of-justice',
      type: 'movie',
      title: 'Batman v Superman: Dawn of Justice',
      releaseYear: 2016,
      genresJson: '["Action","Adventure","Sci-Fi"]',
      creatorsJson: '["Zack Snyder"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/5UsK3grJvtQrtzEgqNlDljJW96w.jpg',
      myRating: 9.2,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'The Ultimate Edition is an operatic mythic tragedy. Ben Affleck warehouse brawl is the greatest live-action Batman combat ever filmed.',
    },
    {
      id: 'movie-berlin',
      slug: 'berlin-money-heist',
      type: 'movie',
      title: 'Berlin (Money Heist)',
      releaseYear: 2023,
      genresJson: '["Action","Crime","Drama","Thriller"]',
      creatorsJson:
        '["\u00c1lex Pina","Esther Mart\u00ednez Lobato","Netflix"]',
      posterUrl: '/images/berlin-poster.jpg',
      myRating: 9.1,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Pedro Alonso delivers a tour-de-force as the iconic, sophisticated jewel thief Andr\u00e9s de Fonollosa in Paris, executing a 44-million-euro heist with romantic flair.',
    },
    {
      id: 'movie-birds-of-prey',
      slug: 'birds-of-prey',
      type: 'movie',
      title: 'Birds of Prey',
      releaseYear: 2020,
      genresJson: '["Action","Comedy","Crime"]',
      creatorsJson: '["Cathy Yan"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/h4VB6m0RwcicVEZvzftYZyKXs6K.jpg',
      myRating: 8.7,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'Colorful R-rated roller-skate fight choreography by 87eleven and Ewan McGregor eccentric Black Mask.',
    },
    {
      id: 'movie-black-adam',
      slug: 'black-adam',
      type: 'movie',
      title: 'Black Adam',
      releaseYear: 2022,
      genresJson: '["Action","Fantasy","Sci-Fi"]',
      creatorsJson: '["Jaume Collet-Serra"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/rCtreCr4xiYEWDQTebybolIh6Xe.jpg',
      myRating: 8.3,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'Dwayne Johnson brutal ancient antihero and Pierce Brosnan scene-stealing gravitas as Doctor Fate.',
    },
    {
      id: 'movie-black-panther',
      slug: 'black-panther',
      type: 'movie',
      title: 'Black Panther',
      releaseYear: 2018,
      genresJson: '["Action","Adventure","Sci-Fi"]',
      creatorsJson: '["Ryan Coogler","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/5WRGN4lwJf7xrewfqY6I5aUmlEI.jpg',
      myRating: 9.3,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Wakandan afrofuturism, Ludwig G\u00f6ransson talking drum score, and Michael B. Jordan Killmonger sympathetic grief.',
    },
    {
      id: 'movie-black-panther-wakanda-forever',
      slug: 'black-panther-wakanda-forever',
      type: 'movie',
      title: 'Black Panther: Wakanda Forever',
      releaseYear: 2022,
      genresJson: '["Action","Adventure","Drama"]',
      creatorsJson: '["Ryan Coogler","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/55emwsc0NYebFXSTEu39zN2Rffq.jpg',
      myRating: 9.1,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Heartbreaking tribute to Chadwick Boseman, Tenoch Huerta charismatic Namor, and Angela Bassett powerhouse presence.',
    },
    {
      id: 'movie-black-widow',
      slug: 'black-widow',
      type: 'movie',
      title: 'Black Widow',
      releaseYear: 2021,
      genresJson: '["Action","Adventure","Thriller"]',
      creatorsJson: '["Cate Shortland","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/qAZ0pzat24kLdO3o8ejmbLxyOac.jpg',
      myRating: 8.7,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'Grounded Bourne-style espionage with Florence Pugh magnetic debut as Yelena Belova.',
    },
    {
      id: 'movie-blade-runner-2049',
      slug: 'blade-runner-2049',
      type: 'movie',
      title: 'Blade Runner 2049',
      releaseYear: 2017,
      genresJson: '["Drama","Mystery","Sci-Fi"]',
      creatorsJson: '["Denis Villeneuve"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
      myRating: 9.7,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'Roger Deakins orange Las Vegas haze, holographic Joi, and Officer K quiet dying snowfall realization of humanity.',
    },
    {
      id: 'movie-blue-beetle',
      slug: 'blue-beetle',
      type: 'movie',
      title: 'Blue Beetle',
      releaseYear: 2023,
      genresJson: '["Action","Adventure","Sci-Fi"]',
      creatorsJson: '["\u00c1ngel Manuel Soto"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/mXLOHHc1Zeuwsl4xYKjKh2280oL.jpg',
      myRating: 8.7,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'Warm Reyes family heart, buster-sword armor weapons, and authentic Mexican-American representation.',
    },
    {
      id: 'movie-captain-america-brave-new-world',
      slug: 'captain-america-brave-new-world',
      type: 'movie',
      title: 'Captain America: Brave New World',
      releaseYear: 2025,
      genresJson: '["Action","Adventure","Sci-Fi"]',
      creatorsJson: '["Julius Onah","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/pzIddUEMWhWzfvLI3TwxUG2wGoi.jpg',
      myRating: 8.9,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'Anthony Mackie stepping fully into the shield with Harrison Ford as Thaddeus Ross and Red Hulk clash.',
    },
    {
      id: 'movie-captain-america-civil-war',
      slug: 'captain-america-civil-war',
      type: 'movie',
      title: 'Captain America: Civil War',
      releaseYear: 2016,
      genresJson: '["Action","Sci-Fi","Thriller"]',
      creatorsJson: '["Anthony Russo","Joe Russo","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/rAGiXaUfPzY7CDEyNKUofk3Kw2e.jpg',
      myRating: 9.4,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Ideological clash between Steve and Tony with peak airport choreography and emotional Siberian climax.',
    },
    {
      id: 'movie-captain-america-the-first-avenger',
      slug: 'captain-america-the-first-avenger',
      type: 'movie',
      title: 'Captain America: The First Avenger',
      releaseYear: 2011,
      genresJson: '["Action","Adventure","Sci-Fi"]',
      creatorsJson: '["Joe Johnston","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/vSNxAJTlD0r02V9sPYpOjqDZXUK.jpg',
      myRating: 8.9,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'Vintage WWII pulp heroism. Steve Rogers throwing himself on the fake grenade showed what made him worthy.',
    },
    {
      id: 'movie-captain-america-the-winter-soldier',
      slug: 'captain-america-the-winter-soldier',
      type: 'movie',
      title: 'Captain America: The Winter Soldier',
      releaseYear: 2014,
      genresJson: '["Action","Sci-Fi","Thriller"]',
      creatorsJson: '["Anthony Russo","Joe Russo","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/tVFRpFw3xTedgPGqxW0AOI8Qhh0.jpg',
      myRating: 9.7,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'Peak political paranoia thriller. The elevator fight, highway knife combat, and the fall of S.H.I.E.L.D.',
    },
    {
      id: 'movie-captain-marvel',
      slug: 'captain-marvel',
      type: 'movie',
      title: 'Captain Marvel',
      releaseYear: 2019,
      genresJson: '["Action","Adventure","Sci-Fi"]',
      creatorsJson: '["Anna Boden","Ryan Fleck","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg',
      myRating: 8.4,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        '90s Blockbuster nostalgia, de-aged Nick Fury, Goose the Flerken, and Carol Danvers binary cosmic awakening.',
    },
    {
      id: 'movie-constantine',
      slug: 'constantine',
      type: 'movie',
      title: 'Constantine',
      releaseYear: 2005,
      genresJson: '["Fantasy","Horror","Mystery"]',
      creatorsJson: '["Francis Lawrence"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/vPYgvd2MwHlxTamAOjwVQp4qs1W.jpg',
      myRating: 9.1,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Keanu Reeves chain-smoking occult exorcist and Peter Stormare iconic portrayal of Lucifer barefoot in white.',
    },
    {
      id: 'movie-deadpool',
      slug: 'deadpool-2016',
      type: 'movie',
      title: 'Deadpool',
      releaseYear: 2016,
      genresJson: '["Action","Comedy","Superhero"]',
      creatorsJson: '["Tim Miller","20th Century Fox","Marvel Entertainment"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/3E53WEZJqP6aM84D8CckXx4pIHw.jpg',
      myRating: 9.3,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Ryan Reynolds passion project shattered R-rated box office records with relentless fourth-wall breaks, maximum effort gory action, and genuine heart.',
    },
    {
      id: 'movie-deadpool-and-wolverine',
      slug: 'deadpool-and-wolverine',
      type: 'movie',
      title: 'Deadpool & Wolverine',
      releaseYear: 2024,
      genresJson: '["Action","Comedy","Sci-Fi"]',
      creatorsJson: '["Shawn Levy","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
      myRating: 9.4,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Hugh Jackman in the comic-accurate yellow spandex fighting Ryan Reynolds to Madonna Like a Prayer. Unapologetic R-rated fan service at its peak.',
    },
    {
      id: 'movie-deadpool-2',
      slug: 'deadpool-2-2018',
      type: 'movie',
      title: 'Deadpool 2',
      releaseYear: 2018,
      genresJson: '["Action","Comedy","Superhero"]',
      creatorsJson:
        '["David Leitch","20th Century Fox","Marvel Entertainment"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/to0spRl1CMDvyUbOnbb4fTk3VAd.jpg',
      myRating: 9.1,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Josh Brolin gritty time-traveling Cable, Zazie Beetz luck-powered Domino, the hysterical X-Force skydiving disaster, and David Leitch slick action choreography.',
    },
    {
      id: 'movie-dhurandhar',
      slug: 'dhurandhar',
      type: 'movie',
      title: 'Dhurandhar',
      releaseYear: 2025,
      genresJson: '["Action","Crime","Espionage","Thriller"]',
      creatorsJson: '["Aditya Dhar"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/8FHOtUpNIk5ZPEay2N2EY5lrxkv.jpg',
      myRating: 9.3,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Ranveer Singh undercover as Jaskirat Singh Rangi infiltrating Karachi Lyari terror networks in Aditya Dhar explosive espionage epic.',
    },
    {
      id: 'movie-dhurandhar-the-revenge',
      slug: 'dhurandhar-the-revenge',
      type: 'movie',
      title: 'Dhurandhar: The Revenge',
      releaseYear: 2026,
      genresJson: '["Action","Espionage","Thriller"]',
      creatorsJson: '["Aditya Dhar"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/ov8vrRLZGoXHpYjSY9Vpv1tHJX7.jpg',
      myRating: 9.4,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'The high-octane second chapter concluding the geopolitical cross-border retribution arc with Sanjay Dutt and Akshaye Khanna.',
    },
    {
      id: 'movie-doctor-strange',
      slug: 'doctor-strange',
      type: 'movie',
      title: 'Doctor Strange',
      releaseYear: 2016,
      genresJson: '["Action","Fantasy","Sci-Fi"]',
      creatorsJson: '["Scott Derrickson","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/uGBVj3bEbCoZbDjjl9wTxcygko1.jpg',
      myRating: 9.0,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Mind-bending kaleidoscope mirror dimensions and the ingenious Dormammu time loop bargain.',
    },
    {
      id: 'movie-doctor-strange-multiverse-of-madness',
      slug: 'doctor-strange-in-the-multiverse-of-madness',
      type: 'movie',
      title: 'Doctor Strange in the Multiverse of Madness',
      releaseYear: 2022,
      genresJson: '["Action","Adventure","Horror"]',
      creatorsJson: '["Sam Raimi","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/eFG27C4cPalzTn99zl40YZcTXMI.jpg',
      myRating: 8.8,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'Full unhinged Sam Raimi horror aesthetics, musical note combat, and Elizabeth Olsen Scarlet Witch terrifying rampage.',
    },
    {
      id: 'movie-dunkirk',
      slug: 'dunkirk',
      type: 'movie',
      title: 'Dunkirk',
      releaseYear: 2017,
      genresJson: '["Action","Drama","History","War"]',
      creatorsJson: '["Christopher Nolan"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/b4Oe15CGLL61Ped0RAS9JpqdmCt.jpg',
      myRating: 9.4,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Pure experiential cinema. The interlocking temporal crosscuts of The Mole (one week), The Sea (one day), and The Air (one hour) are relentless.',
    },
    {
      id: 'movie-eternals',
      slug: 'eternals',
      type: 'movie',
      title: 'Eternals',
      releaseYear: 2021,
      genresJson: '["Action","Adventure","Drama"]',
      creatorsJson: '["Chlo\u00e9 Zhao","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/lFByFSLV5WDJEv3KabbdAF959F2.jpg',
      myRating: 8.6,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'Chlo\u00e9 Zhao natural golden-hour cinematography and cosmic philosophical scale spanning 7,000 years of human history.',
    },
    {
      id: 'movie-fantastic-four-2005',
      slug: 'fantastic-four-2005',
      type: 'movie',
      title: 'Fantastic Four',
      releaseYear: 2005,
      genresJson: '["Action","Adventure","Fantasy"]',
      creatorsJson: '["Tim Story"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/4YMcYEFS8sFuW3soP1HVmgR3cSm.jpg',
      myRating: 7.5,
      watchStatus: 'completed',
      tier: 'canon',
      personalReview:
        'Chris Evans charismatic Johnny Storm, Michael Chiklis practical Ben Grimm suit, and the iconic Brooklyn Bridge sequence.',
    },
    {
      id: 'movie-following',
      slug: 'following',
      type: 'movie',
      title: 'Following',
      releaseYear: 1998,
      genresJson: '["Crime","Mystery","Thriller"]',
      creatorsJson: '["Christopher Nolan"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/3bX6VVSMf0dvzk5pMT4ALG5A92d.jpg',
      myRating: 8.5,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'Nolan micro-budget neo-noir debut. The non-linear structure and obsessive voyeurism established his signature architectural storytelling.',
    },
    {
      id: 'movie-free-guy',
      slug: 'free-guy',
      type: 'movie',
      title: 'Free Guy',
      releaseYear: 2021,
      genresJson: '["Action","Comedy","Sci-Fi"]',
      creatorsJson: '["Shawn Levy"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/dxraF0qPr1OEgJk17ltQTO84kQF.jpg',
      myRating: 9.1,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Ryan Reynolds NPC bank teller breaking free of his video game programming. The Captain America shield and lightsaber cameos were joyous.',
    },
    {
      id: 'movie-godzilla-2014',
      slug: 'godzilla-2014',
      type: 'movie',
      title: 'Godzilla',
      releaseYear: 2014,
      genresJson: '["Action","Sci-Fi","Monster"]',
      creatorsJson: '["Gareth Edwards","Legendary Pictures"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/tphkjmQq8WebuVwNXelmjLUXuPJ.jpg',
      myRating: 9.1,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Gareth Edwards masterclass in scale and patience. The HALO jump sequence into San Francisco and the blue atomic breath reveal remain unforgettable.',
    },
    {
      id: 'movie-godzilla-vs-kong',
      slug: 'godzilla-vs-kong',
      type: 'movie',
      title: 'Godzilla vs. Kong',
      releaseYear: 2021,
      genresJson: '["Action","Sci-Fi","Adventure"]',
      creatorsJson: '["Adam Wingard","Legendary Pictures"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/pgqgaUx1cJb5oZQQ5v0tNARCeBp.jpg',
      myRating: 9.3,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Neon-soaked Hong Kong climax and Hollow Earth world-building. Pure unadulterated cinematic adrenaline.',
    },
    {
      id: 'movie-godzilla-x-kong-the-new-empire',
      slug: 'godzilla-x-kong-the-new-empire',
      type: 'movie',
      title: 'Godzilla x Kong: The New Empire',
      releaseYear: 2024,
      genresJson: '["Action","Sci-Fi","Adventure"]',
      creatorsJson: '["Adam Wingard","Legendary Pictures"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg',
      myRating: 8.9,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'High-energy Saturday morning cartoon energy blown up to IMAX scale. Kong with the B.E.A.S.T. glove and pink evolved Godzilla.',
    },
    {
      id: 'movie-godzilla-king-of-the-monsters',
      slug: 'godzilla-king-of-the-monsters',
      type: 'movie',
      title: 'Godzilla: King of the Monsters',
      releaseYear: 2019,
      genresJson: '["Action","Sci-Fi","Fantasy"]',
      creatorsJson: '["Michael Dougherty","Legendary Pictures"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/mzOHg7Q5q9yUmY0b9Esu8Qe6Nnm.jpg',
      myRating: 9.2,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Mythic, biblical titan warfare. Bear McCreary orchestral score blending classic Ifukube themes with King Ghidorah and Mothra was glorious.',
    },
    {
      id: 'movie-guardians-of-the-galaxy',
      slug: 'guardians-of-the-galaxy',
      type: 'movie',
      title: 'Guardians of the Galaxy',
      releaseYear: 2014,
      genresJson: '["Action","Adventure","Sci-Fi"]',
      creatorsJson: '["James Gunn","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg',
      myRating: 9.4,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Awesome Mix Vol. 1, cosmic heart, and a ragtag band of galactic outlaws bonding into an inseparable family.',
    },
    {
      id: 'movie-guardians-of-the-galaxy-vol-2',
      slug: 'guardians-of-the-galaxy-vol-2',
      type: 'movie',
      title: 'Guardians of the Galaxy Vol. 2',
      releaseYear: 2017,
      genresJson: '["Action","Adventure","Comedy"]',
      creatorsJson: '["James Gunn","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/y4MBh0EjBlMuOzv9axM4qJlmhzz.jpg',
      myRating: 9.2,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Deep emotional exploration of toxic fathers versus found family. Yondu Ravager funeral to Father and Son broke me.',
    },
    {
      id: 'movie-guardians-of-the-galaxy-vol-3',
      slug: 'guardians-of-the-galaxy-vol-3',
      type: 'movie',
      title: 'Guardians of the Galaxy Vol. 3',
      releaseYear: 2023,
      genresJson: '["Action","Adventure","Comedy"]',
      creatorsJson: '["James Gunn","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg',
      myRating: 9.5,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'Heart-wrenching and triumphant conclusion. Rocket origin story, the hallway fight to Beastie Boys, and pure emotional resonance.',
    },
    {
      id: 'movie-inception',
      slug: 'inception',
      type: 'movie',
      title: 'Inception',
      releaseYear: 2010,
      genresJson: '["Action","Sci-Fi","Thriller"]',
      creatorsJson: '["Christopher Nolan"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg',
      myRating: 9.8,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'Simultaneous multi-tier temporal dream heist. Zero-gravity hallway fight and Hans Zimmer Time transcend filmmaking.',
    },
    {
      id: 'movie-insomnia',
      slug: 'insomnia',
      type: 'movie',
      title: 'Insomnia',
      releaseYear: 2002,
      genresJson: '["Crime","Drama","Mystery"]',
      creatorsJson: '["Christopher Nolan"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/riVXh3EimGO0y5dgQxEWPRy5Itg.jpg',
      myRating: 8.8,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'Atmospheric cat-and-mouse duel under the midnight Alaskan sun. Al Pacino sleep-deprived detective meets Robin Williams chilling killer.',
    },
    {
      id: 'movie-interstellar',
      slug: 'interstellar',
      type: 'movie',
      title: 'Interstellar',
      releaseYear: 2014,
      genresJson: '["Adventure","Drama","Sci-Fi"]',
      creatorsJson: '["Christopher Nolan"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg',
      myRating: 9.9,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'Docking scene with No Time for Caution, Gargantua black hole, and the fifth dimension tesseract. A profound testament to human ambition.',
    },
    {
      id: 'movie-iron-man',
      slug: 'iron-man',
      type: 'movie',
      title: 'Iron Man',
      releaseYear: 2008,
      genresJson: '["Action","Sci-Fi","Superhero"]',
      creatorsJson: '["Jon Favreau","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/78lPtwv72eTNqFW9COBYI0dWDJa.jpg',
      myRating: 9.2,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'The foundation of the MCU. Robert Downey Jr. is electrifying as Tony Stark forging Mark I in the cave.',
    },
    {
      id: 'movie-iron-man-2',
      slug: 'iron-man-2',
      type: 'movie',
      title: 'Iron Man 2',
      releaseYear: 2010,
      genresJson: '["Action","Sci-Fi","Superhero"]',
      creatorsJson: '["Jon Favreau","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/6WBeq4fCfn7AN0o21W9qNcRF2l9.jpg',
      myRating: 8.6,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'Monaco Grand Prix briefcase suit-up and the introduction of Natasha Romanoff and James Rhodes War Machine.',
    },
    {
      id: 'movie-iron-man-3',
      slug: 'iron-man-3',
      type: 'movie',
      title: 'Iron Man 3',
      releaseYear: 2013,
      genresJson: '["Action","Sci-Fi","Thriller"]',
      creatorsJson: '["Shane Black","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/qhPtAc1TKbMPqNvcdXSOn9Bn7hZ.jpg',
      myRating: 8.8,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'Shane Black buddy-cop deconstruction of Tony Stark PTSD and the House Party Protocol armor swarm.',
    },
    {
      id: 'movie-joker',
      slug: 'joker',
      type: 'movie',
      title: 'Joker',
      releaseYear: 2019,
      genresJson: '["Crime","Drama","Thriller"]',
      creatorsJson: '["Todd Phillips"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
      myRating: 9.4,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'Joaquin Phoenix transformative Academy Award performance. A haunting psychological descent scored by Hildur Gu\u00f0nad\u00f3ttir cello.',
    },
    {
      id: 'movie-joker-folie-a-deux',
      slug: 'joker-folie-a-deux',
      type: 'movie',
      title: 'Joker: Folie \u00e0 Deux',
      releaseYear: 2024,
      genresJson: '["Crime","Drama","Musical"]',
      creatorsJson: '["Todd Phillips"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/if8QiqCI7WAGImKcJCfzp6VTyKA.jpg',
      myRating: 8.6,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'Joaquin Phoenix and Lady Gaga Harley Quinn in a surreal psychological courtroom melodrama exploring shared madness.',
    },
    {
      id: 'movie-jolly-llb',
      slug: 'jolly-llb',
      type: 'movie',
      title: 'Jolly LLB',
      releaseYear: 2013,
      genresJson: '["Comedy","Drama"]',
      creatorsJson: '["Subhash Kapoor"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/bwRoU9p5GvjxgPfmIgsfcJ4ydng.jpg',
      myRating: 9.1,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Arshad Warsi underdog small-town lawyer taking down high-profile advocate Boman Irani before Saurabh Shukla unforgettable Judge Tripathi.',
    },
    {
      id: 'movie-jolly-llb-2',
      slug: 'jolly-llb-2',
      type: 'movie',
      title: 'Jolly LLB 2',
      releaseYear: 2017,
      genresJson: '["Comedy","Drama","Crime"]',
      creatorsJson: '["Subhash Kapoor"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/n9MjoGmaYagaaETCQP0S6Ch3JLH.jpg',
      myRating: 9.0,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Akshay Kumar in Lucknow fighting a fake encounter case with Annu Kapoor fierce opposition and powerful courtroom monologues.',
    },
    {
      id: 'movie-jolly-llb-3',
      slug: 'jolly-llb-3',
      type: 'movie',
      title: 'Jolly LLB 3',
      releaseYear: 2025,
      genresJson: '["Comedy","Drama"]',
      creatorsJson: '["Subhash Kapoor"]',
      posterUrl: '/images/jolly-llb-3.jpg',
      myRating: 9.2,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'The long-awaited courtroom showdown between original Jolly Arshad Warsi and Jolly 2 Akshay Kumar with Judge Saurabh Shukla presiding.',
    },
    {
      id: 'movie-justice-league-2017',
      slug: 'justice-league-2017',
      type: 'movie',
      title: 'Justice League',
      releaseYear: 2017,
      genresJson: '["Action","Adventure","Sci-Fi"]',
      creatorsJson: '["Zack Snyder","Joss Whedon"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/eifGNCSDuxJeS1loAXil5bIGgvC.jpg',
      myRating: 7.9,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'The historical 2017 theatrical assembly that paved the way for the fan movement to restore the director vision.',
    },
    {
      id: 'movie-kgf-chapter-1',
      slug: 'kgf-chapter-1',
      type: 'movie',
      title: 'K.G.F: Chapter 1',
      releaseYear: 2018,
      genresJson: '["Action","Crime","Drama"]',
      creatorsJson: '["Prashanth Neel"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/ltHlJwvxKv7d0ooCiKSAvfwV9tX.jpg',
      myRating: 9.4,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Rocky Bhai rise from Bombay slums into Kolar Gold Fields. Electric editing cuts, world-class BGM, and non-linear mass heroism.',
    },
    {
      id: 'movie-kgf-chapter-2',
      slug: 'kgf-chapter-2',
      type: 'movie',
      title: 'K.G.F: Chapter 2',
      releaseYear: 2022,
      genresJson: '["Action","Crime","Drama"]',
      creatorsJson: '["Prashanth Neel"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/khNVygolU0TxLIDWff5tQlAhZ23.jpg',
      myRating: 9.5,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'Kalashnikov police station scene is the pinnacle of elevation cinema. Uncompromising scale, swagger, and tragedy.',
    },
    {
      id: 'movie-kantara',
      slug: 'kantara',
      type: 'movie',
      title: 'Kantara',
      releaseYear: 2022,
      genresJson: '["Action","Drama","Folklore","Thriller"]',
      creatorsJson: '["Rishab Shetty"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/jIsKmkxMzdCZ0Ux1GVSnu8m6Na6.jpg',
      myRating: 9.6,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'The final 20 minutes of Bhoota Kola spirit possession and Varaha Roopam climax is pure divine goosebumps. Raw indigenous storytelling at its zenith.',
    },
    {
      id: 'movie-kantara-chapter-1',
      slug: 'kantara-chapter-1',
      type: 'movie',
      title: 'Kantara: Chapter 1',
      releaseYear: 2025,
      genresJson: '["Action","Drama","Folklore","Mythology"]',
      creatorsJson: '["Rishab Shetty"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/ehQPboTPaIMkMUOoNOh8e7pZ5Rp.jpg',
      myRating: 9.5,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'The mythic prequel exploring the reign of the Kadamba dynasty and the origins of the sacred forest spirit deity.',
    },
    {
      id: 'movie-kong-skull-island',
      slug: 'kong-skull-island',
      type: 'movie',
      title: 'Kong: Skull Island',
      releaseYear: 2017,
      genresJson: '["Action","Adventure","Fantasy"]',
      creatorsJson: '["Jordan Vogt-Roberts","Legendary Pictures"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/r2517Vz9EhDhj88qwbDVj8DCRZN.jpg',
      myRating: 9.0,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Vietnam-era psychedelic rock aesthetic meets colossal monster brawls. Stellar cinematography with striking silhouette shots.',
    },
    {
      id: 'movie-logan',
      slug: 'logan-2017',
      type: 'movie',
      title: 'Logan',
      releaseYear: 2017,
      genresJson: '["Action","Drama","Sci-Fi","Western"]',
      creatorsJson:
        '["James Mangold","20th Century Fox","Marvel Entertainment"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/fnbjcRDYn6YviCcePDnGdyAkYsB.jpg',
      myRating: 9.8,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'A somber, visceral neo-Western masterpiece. Hugh Jackman weary, ailing Wolverine and Patrick Stewart dementia-plagued Professor X elevate superhero cinema to Shakespearean tragedy.',
    },
    {
      id: 'movie-man-of-steel',
      slug: 'man-of-steel',
      type: 'movie',
      title: 'Man of Steel',
      releaseYear: 2013,
      genresJson: '["Action","Sci-Fi","Superhero"]',
      creatorsJson: '["Zack Snyder"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/8GFtkImmK0K1VaUChR0n9O61CFU.jpg',
      myRating: 8.9,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'First flight scene scored by Hans Zimmer Flight is pure cinematic elevation. Grounded visceral Kryptonian combat.',
    },
    {
      id: 'movie-memento',
      slug: 'memento',
      type: 'movie',
      title: 'Memento',
      releaseYear: 2000,
      genresJson: '["Mystery","Thriller"]',
      creatorsJson: '["Christopher Nolan"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/nzlv62aC0octS5AklAiWpXLX9Z0.jpg',
      myRating: 9.6,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'The reverse chronology structure is pure narrative genius that puts you directly inside Leonard anterograde amnesia.',
    },
    {
      id: 'movie-morbius',
      slug: 'morbius',
      type: 'movie',
      title: 'Morbius',
      releaseYear: 2022,
      genresJson: '["Action","Horror","Sci-Fi"]',
      creatorsJson: '["Daniel Espinosa","Sony Pictures"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/Av8Z2jZhEm1FLkFzMThzz9hndJF.jpg',
      myRating: 7.9,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'Jared Leto living vampire transformation and smoke trail echolocation effects in the NY subway.',
    },
    {
      id: 'movie-mufasa-the-lion-king',
      slug: 'mufasa-the-lion-king',
      type: 'movie',
      title: 'Mufasa: The Lion King',
      releaseYear: 2024,
      genresJson: '["Adventure","Drama","Family"]',
      creatorsJson: '["Barry Jenkins","Walt Disney"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/jbOSUAWMGzGL1L4EaUF8K6zYFo7.jpg',
      myRating: 8.9,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'Barry Jenkins lyrical visual direction telling the untold brotherhood origin between orphaned Mufasa and Taka.',
    },
    {
      id: 'movie-munjya',
      slug: 'munjya',
      type: 'movie',
      title: 'Munjya',
      releaseYear: 2024,
      genresJson: '["Comedy","Horror","Folklore"]',
      creatorsJson: '["Aditya Sarpotdar","Maddock Films"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/ylYdXu0SM79Qs7vOz6q7mBxanVD.jpg',
      myRating: 8.8,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'Great blend of Konkan folklore, sharp comedy, and genuine horror VFX in the Maddock supernatural universe.',
    },
    {
      id: 'movie-oppenheimer',
      slug: 'oppenheimer',
      type: 'movie',
      title: 'Oppenheimer',
      releaseYear: 2023,
      genresJson: '["Biography","Drama","History"]',
      creatorsJson: '["Christopher Nolan"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
      myRating: 9.8,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'Trinity test silence and the haunting gym stomping sequence. Cillian Murphy eyes capture the existential terror of unleashing the atomic age.',
    },
    {
      id: 'movie-pokemon-the-movie-2000',
      slug: 'pokemon-the-movie-2000',
      type: 'movie',
      title: 'Pok\u00e9mon: The Movie 2000',
      releaseYear: 1999,
      genresJson: '["Animation","Action","Adventure","Fantasy"]',
      creatorsJson: '["Kunihiko Yuyama"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/6u65C8aG4krAVyHsTjAMF7ucTDH.jpg',
      myRating: 9.0,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Lugia rising from the whirlpool with the legendary bird trio Zapdos, Articuno, and Moltres in nostalgic childhood glory.',
    },
    {
      id: 'movie-shang-chi',
      slug: 'shang-chi-and-the-legend-of-the-ten-rings',
      type: 'movie',
      title: 'Shang-Chi and the Legend of the Ten Rings',
      releaseYear: 2021,
      genresJson: '["Action","Adventure","Fantasy"]',
      creatorsJson: '["Destin Daniel Cretton","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/9f2Q0U3IOsLgrI2HkvldwSABZy5.jpg',
      myRating: 9.2,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Breathtaking wuxia and bus martial arts choreography with Tony Leung giving Wenwu profound soul.',
    },
    {
      id: 'movie-shazam',
      slug: 'shazam',
      type: 'movie',
      title: 'Shazam!',
      releaseYear: 2019,
      genresJson: '["Action","Comedy","Fantasy"]',
      creatorsJson: '["David F. Sandberg"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/xnopI5Xtky18MPhK40cZAGAOVeV.jpg',
      myRating: 8.8,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'Big meets Superman. Zachary Levi brings infectious childlike wonder discovering his lightning powers.',
    },
    {
      id: 'movie-shazam-fury-of-the-gods',
      slug: 'shazam-fury-of-the-gods',
      type: 'movie',
      title: 'Shazam! Fury of the Gods',
      releaseYear: 2023,
      genresJson: '["Action","Adventure","Comedy"]',
      creatorsJson: '["David F. Sandberg"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/3GrRgt6CiLIUXUtoktcv1g2iwT5.jpg',
      myRating: 8.2,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'Daughters of Atlas mythical beasts invading Philadelphia with fun Shazamily team dynamics.',
    },
    {
      id: 'movie-spiderman-2002',
      slug: 'spiderman-2002',
      type: 'movie',
      title: 'Spider-Man',
      releaseYear: 2002,
      genresJson: '["Action","Sci-Fi","Superhero"]',
      creatorsJson: '["Sam Raimi","Marvel Entertainment","Columbia Pictures"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/or6XJBVpcEbIkma0V9zshnbEtx4.jpg',
      myRating: 9.5,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'Sam Raimi foundational superhero triumph. Tobey Maguire earnest Peter Parker, Willem Dafoe unhinged Green Goblin, and the timeless upside-down rain kiss.',
    },
    {
      id: 'movie-spiderman-2-2004',
      slug: 'spiderman-2-2004',
      type: 'movie',
      title: 'Spider-Man 2',
      releaseYear: 2004,
      genresJson: '["Action","Sci-Fi","Superhero"]',
      creatorsJson: '["Sam Raimi","Marvel Entertainment","Columbia Pictures"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/aGuvNAaaZuWXYQQ6N2v7DeuP6mB.jpg',
      myRating: 9.8,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'One of the greatest comic book movies ever crafted. Alfred Molina tragic Otto Octavius, the heart-stopping runaway train sequence, and Peter sacrifice of personal happiness for responsibility.',
    },
    {
      id: 'movie-spiderman-3-2007',
      slug: 'spiderman-3-2007',
      type: 'movie',
      title: 'Spider-Man 3',
      releaseYear: 2007,
      genresJson: '["Action","Sci-Fi","Superhero"]',
      creatorsJson: '["Sam Raimi","Marvel Entertainment","Columbia Pictures"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/qFmwhVUoUSXjkKRmca5yGDEXBIj.jpg',
      myRating: 9.0,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'The original live-action cinematic arrival of Venom and the black alien symbiote suit. Topher Grace Eddie Brock transformation, Sandman birth tragedy, and high-octane web-slinging showdowns.',
    },
    {
      id: 'movie-spider-man-across-the-spider-verse',
      slug: 'spider-man-across-the-spider-verse',
      type: 'movie',
      title: 'Spider-Man: Across the Spider-Verse',
      releaseYear: 2023,
      genresJson: '["Animation","Action","Adventure"]',
      creatorsJson: '["Joaquim Dos Santos","Kemp Powers","Justin K. Thompson"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
      myRating: 9.8,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'A dizzying symphonic tour de force across Mumbattan, Nueva York, and Earth-42. Daniel Pemberton score is god-tier.',
    },
    {
      id: 'movie-spider-man-far-from-home',
      slug: 'spider-man-far-from-home',
      type: 'movie',
      title: 'Spider-Man: Far From Home',
      releaseYear: 2019,
      genresJson: '["Action","Adventure","Comedy"]',
      creatorsJson: '["Jon Watts","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/4q2NNj4S5dG2RLF9CpXsej7yXl.jpg',
      myRating: 9.0,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Jake Gyllenhaal Mysterio illusion sequence in Berlin is one of the most visually inventive scenes in comic book cinema.',
    },
    {
      id: 'movie-spider-man-homecoming',
      slug: 'spider-man-homecoming',
      type: 'movie',
      title: 'Spider-Man: Homecoming',
      releaseYear: 2017,
      genresJson: '["Action","Adventure","Comedy"]',
      creatorsJson: '["Jon Watts","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg',
      myRating: 9.1,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'John Hughes high school vibe meets web-slinging. Michael Keaton Vulture car talk scene was masterclass tension.',
    },
    {
      id: 'movie-spider-man-into-the-spider-verse',
      slug: 'spider-man-into-the-spider-verse',
      type: 'movie',
      title: 'Spider-Man: Into the Spider-Verse',
      releaseYear: 2018,
      genresJson: '["Animation","Action","Adventure"]',
      creatorsJson: '["Bob Persichetti","Peter Ramsey","Rodney Rothman"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg',
      myRating: 9.8,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'What Up Danger leap of faith. Redefined visual animation grammar and storytelling for the 21st century.',
    },
    {
      id: 'movie-spider-man-no-way-home',
      slug: 'spider-man-no-way-home',
      type: 'movie',
      title: 'Spider-Man: No Way Home',
      releaseYear: 2021,
      genresJson: '["Action","Adventure","Fantasy"]',
      creatorsJson: '["Jon Watts","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/tJ44EffQBBUMc61xa8QDz0oijQT.jpg',
      myRating: 9.3,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Three generations of Peter Parkers sharing the screen. Cathartic redemption arc for Andrew Garfield and Tobey Maguire.',
    },
    {
      id: 'movie-suicide-squad',
      slug: 'suicide-squad',
      type: 'movie',
      title: 'Suicide Squad',
      releaseYear: 2016,
      genresJson: '["Action","Adventure","Fantasy"]',
      creatorsJson: '["David Ayer"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/sk3FZgh3sRrmr8vyhaitNobMcfh.jpg',
      myRating: 8.1,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'Margot Robbie star-making performance as Harley Quinn and Will Smith Deadshot alley shooting demo.',
    },
    {
      id: 'movie-supergirl-1984',
      slug: 'supergirl-1984',
      type: 'movie',
      title: 'Supergirl',
      releaseYear: 1984,
      genresJson: '["Action","Adventure","Sci-Fi"]',
      creatorsJson: '["Jeannot Szwarc"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/o49a2RDChZkry84LomEORCPDWfk.jpg',
      myRating: 7.2,
      watchStatus: 'completed',
      tier: 'canon',
      personalReview:
        'Helen Slater charming performance as Kara Zor-El, flying past the Statue of Liberty with Jerry Goldsmith soaring orchestral score.',
    },
    {
      id: 'movie-superman-1978',
      slug: 'superman-1978',
      type: 'movie',
      title: 'Superman',
      releaseYear: 1978,
      genresJson: '["Action","Adventure","Sci-Fi"]',
      creatorsJson: '["Richard Donner"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/d7px1FQxW4tngdACVRsCSaZq0Xl.jpg',
      myRating: 9.4,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'You will believe a man can fly. Christopher Reeve defines the Man of Steel forever alongside Marlon Brando and John Williams immortal march.',
    },
    {
      id: 'movie-tangled',
      slug: 'tangled',
      type: 'movie',
      title: 'Tangled',
      releaseYear: 2010,
      genresJson: '["Animation","Comedy","Fantasy","Musical"]',
      creatorsJson: '["Nathan Greno","Byron Howard","Walt Disney"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/ym7Kst6a4uodryxqbGOxmewF235.jpg',
      myRating: 9.3,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'I See the Light floating lantern sequence is one of Disney most enchanting visual achievements. Maximus the horse stole every scene.',
    },
    {
      id: 'movie-tenet',
      slug: 'tenet',
      type: 'movie',
      title: 'Tenet',
      releaseYear: 2020,
      genresJson: '["Action","Sci-Fi","Thriller"]',
      creatorsJson: '["Christopher Nolan"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/f9zhIg8M1X1tFpHFUEA3scA6OYb.jpg',
      myRating: 9.1,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Audacious temporal pincer movement and reverse entropy combat choreography. Ludwig G\u00f6ransson pulse-pounding electronic score.',
    },
    {
      id: 'movie-the-amazing-spiderman',
      slug: 'the-amazing-spiderman-2012',
      type: 'movie',
      title: 'The Amazing Spider-Man',
      releaseYear: 2012,
      genresJson: '["Action","Sci-Fi","Superhero"]',
      creatorsJson: '["Marc Webb","Marvel Entertainment","Columbia Pictures"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/jexoNYnPd6vVrmygwF6QZmWPFdu.jpg',
      myRating: 8.9,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Andrew Garfield kinetic, quip-heavy Peter Parker and unmatched electric romantic chemistry with Emma Stone Gwen Stacy. Grounded swinging dynamics and emotional vulnerability.',
    },
    {
      id: 'movie-the-amazing-spiderman-2',
      slug: 'the-amazing-spiderman-2-2014',
      type: 'movie',
      title: 'The Amazing Spider-Man 2',
      releaseYear: 2014,
      genresJson: '["Action","Sci-Fi","Superhero"]',
      creatorsJson: '["Marc Webb","Marvel Entertainment","Columbia Pictures"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/bU7nTmvmy0h3VUP01v1T2imgH6N.jpg',
      myRating: 8.7,
      watchStatus: 'completed',
      tier: 'canon',
      personalReview:
        'Visually the finest web-slinging VFX ever rendered on screen with Hans Zimmer pounding dubstep Electro score and the devastating clock tower climax.',
    },
    {
      id: 'movie-the-avengers',
      slug: 'the-avengers',
      type: 'movie',
      title: 'The Avengers',
      releaseYear: 2012,
      genresJson: '["Action","Sci-Fi","Superhero"]',
      creatorsJson: '["Joss Whedon","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg',
      myRating: 9.3,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'The historic circular panning shot in New York as all six original Avengers assemble to Alan Silvestri score.',
    },
    {
      id: 'movie-the-batman',
      slug: 'the-batman',
      type: 'movie',
      title: 'The Batman',
      releaseYear: 2022,
      genresJson: '["Action","Crime","Drama","Mystery"]',
      creatorsJson: '["Matt Reeves"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg',
      myRating: 9.5,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'Gritty noir detective masterpiece. Greig Fraser rain-soaked cinematography and Michael Giacchino score create an unmatched atmospheric Gotham.',
    },
    {
      id: 'movie-the-dark-knight',
      slug: 'the-dark-knight',
      type: 'movie',
      title: 'The Dark Knight',
      releaseYear: 2008,
      genresJson: '["Action","Crime","Drama","Thriller"]',
      creatorsJson: '["Christopher Nolan"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
      myRating: 9.9,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'The gold standard of modern cinema. Heath Ledger Joker delivered one of the greatest acting performances in human history.',
    },
    {
      id: 'movie-the-dark-knight-rises',
      slug: 'the-dark-knight-rises',
      type: 'movie',
      title: 'The Dark Knight Rises',
      releaseYear: 2012,
      genresJson: '["Action","Crime","Drama"]',
      creatorsJson: '["Christopher Nolan"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg',
      myRating: 9.2,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Operatic finale to the trilogy. Tom Hardy Bane broke the Bat physically, and Bruce Wayne climb out of the Pit was mythic triumph.',
    },
    {
      id: 'movie-the-flash',
      slug: 'the-flash',
      type: 'movie',
      title: 'The Flash',
      releaseYear: 2023,
      genresJson: '["Action","Adventure","Sci-Fi"]',
      creatorsJson: '["Andy Muschietti"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/rktDFPbfHfUbArZ6OOOKsXcv0Bm.jpg',
      myRating: 8.8,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'Michael Keaton return as Batman in the Batwing and the emotional heart between Barry and his mother in the grocery aisle.',
    },
    {
      id: 'movie-the-incredible-hulk',
      slug: 'the-incredible-hulk',
      type: 'movie',
      title: 'The Incredible Hulk',
      releaseYear: 2008,
      genresJson: '["Action","Sci-Fi","Superhero"]',
      creatorsJson: '["Louis Leterrier","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/gKzYx79y0AQTL4UAk1cBQJ3nvrm.jpg',
      myRating: 8.4,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'Edward Norton troubled Bruce Banner and the visceral Harlem street brawl against the Abomination.',
    },
    {
      id: 'movie-the-lion-king-1994',
      slug: 'the-lion-king',
      type: 'movie',
      title: 'The Lion King',
      releaseYear: 1994,
      genresJson: '["Animation","Adventure","Drama"]',
      creatorsJson: '["Roger Allers","Rob Minkoff","Walt Disney"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg',
      myRating: 9.7,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'Circle of Life sunrise opening on Pride Rock, Hans Zimmer African choral arrangements, and James Earl Jones Mufasa.',
    },
    {
      id: 'movie-the-marvels',
      slug: 'the-marvels',
      type: 'movie',
      title: 'The Marvels',
      releaseYear: 2023,
      genresJson: '["Action","Adventure","Fantasy"]',
      creatorsJson: '["Nia DaCosta","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/9GBhzXMFjgcZ3FdR9w3bUMMTps5.jpg',
      myRating: 8.2,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'Fun quantum entanglement body-swapping combat mechanics and Iman Vellani delightful Ms. Marvel energy.',
    },
    {
      id: 'movie-the-prestige',
      slug: 'the-prestige',
      type: 'movie',
      title: 'The Prestige',
      releaseYear: 2006,
      genresJson: '["Drama","Mystery","Sci-Fi"]',
      creatorsJson: '["Christopher Nolan"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/Ag2B2KHKQPukjH7WutmgnnSNurZ.jpg',
      myRating: 9.7,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'A film built like a magic trick in three acts. The obsessive rivalry between Angier and Borden with Nikola Tesla machine is immaculate cinema.',
    },
    {
      id: 'movie-the-social-network',
      slug: 'the-social-network',
      type: 'movie',
      title: 'The Social Network',
      releaseYear: 2010,
      genresJson: '["Biography","Drama"]',
      creatorsJson: '["David Fincher","Aaron Sorkin"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg',
      myRating: 9.6,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'Sorkin rapid-fire dialogue, Fincher surgical pacing, and Trent Reznor Oscar-winning dark ambient electronic score.',
    },
    {
      id: 'movie-the-suicide-squad-2021',
      slug: 'the-suicide-squad-2021',
      type: 'movie',
      title: 'The Suicide Squad',
      releaseYear: 2021,
      genresJson: '["Action","Adventure","Comedy"]',
      creatorsJson: '["James Gunn"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/6fU04XN1OSJNF4s3YkyEoSDC8Cj.jpg',
      myRating: 9.4,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'James Gunn bloody, anarchic masterpiece. Starro the Conqueror, Bloodsport versus Peacemaker, and King Shark.',
    },
    {
      id: 'movie-thor',
      slug: 'thor',
      type: 'movie',
      title: 'Thor',
      releaseYear: 2011,
      genresJson: '["Action","Fantasy","Superhero"]',
      creatorsJson: '["Kenneth Branagh","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/prSfAi1xGrhLQNxVSUFh61xQ4Qy.jpg',
      myRating: 8.7,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'Shakespearean familial drama in the golden halls of Asgard with Tom Hiddleston definitive debut as Loki.',
    },
    {
      id: 'movie-thor-love-and-thunder',
      slug: 'thor-love-and-thunder',
      type: 'movie',
      title: 'Thor: Love and Thunder',
      releaseYear: 2022,
      genresJson: '["Action","Adventure","Comedy"]',
      creatorsJson: '["Taika Waititi","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/5NrJiiR2OfNWDTVmE67yJUqI9Nj.jpg',
      myRating: 8.3,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'Christian Bale Gorr the God Butcher in the black-and-white Shadow Realm and Guns N Roses soundtrack.',
    },
    {
      id: 'movie-thor-ragnarok',
      slug: 'thor-ragnarok',
      type: 'movie',
      title: 'Thor: Ragnarok',
      releaseYear: 2017,
      genresJson: '["Action","Comedy","Sci-Fi"]',
      creatorsJson: '["Taika Waititi","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg',
      myRating: 9.1,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Immigrant Song blasting on the rainbow bridge while Thor channels lightning without Mjolnir.',
    },
    {
      id: 'movie-thor-the-dark-world',
      slug: 'thor-the-dark-world',
      type: 'movie',
      title: 'Thor: The Dark World',
      releaseYear: 2013,
      genresJson: '["Action","Fantasy","Sci-Fi"]',
      creatorsJson: '["Alan Taylor","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/wp6OxE4poJ4G7c0U2ZIXasTSMR7.jpg',
      myRating: 8.2,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'Loki and Thor banter escaping Asgard and the introduction of the Reality Stone Aether.',
    },
    {
      id: 'movie-thunderbolts',
      slug: 'thunderbolts',
      type: 'movie',
      title: 'Thunderbolts*',
      releaseYear: 2025,
      genresJson: '["Action","Adventure","Crime"]',
      creatorsJson: '["Jake Schreier","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/hqcexYHbiTBfDIdDWxrxPtVndBX.jpg',
      myRating: 8.8,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'Misfit anti-heroes including Yelena Belova, Bucky Barnes, and Red Guardian in gritty black-ops missions.',
    },
    {
      id: 'movie-v-for-vendetta',
      slug: 'v-for-vendetta-2005',
      type: 'movie',
      title: 'V for Vendetta',
      releaseYear: 2005,
      genresJson: '["Action","Drama","Sci-Fi","Thriller"]',
      creatorsJson: '["James McTeigue","The Wachowskis","DC Vertigo"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/piZOwjyk1g51oPHonc7zaQY3WOv.jpg',
      myRating: 9.7,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'Alan Moore dystopian DC masterpiece brought to life. Hugo Weaving eloquent masked revolutionary V, Natalie Portman Evey transformation, and the eternal 5th of November philosophy.',
    },
    {
      id: 'movie-venom',
      slug: 'venom',
      type: 'movie',
      title: 'Venom',
      releaseYear: 2018,
      genresJson: '["Action","Sci-Fi","Comedy"]',
      creatorsJson: '["Ruben Fleischer","Sony Pictures"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/2uNW4WbgBXL25BAbXGLnLqX71Sw.jpg',
      myRating: 8.8,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'Tom Hardy unhinged dual-performance as Eddie Brock and the lobster-eating symbiote is infectious entertainment.',
    },
    {
      id: 'movie-venom-let-there-be-carnage',
      slug: 'venom-let-there-be-carnage',
      type: 'movie',
      title: 'Venom: Let There Be Carnage',
      releaseYear: 2021,
      genresJson: '["Action","Sci-Fi","Thriller"]',
      creatorsJson: '["Andy Serkis","Sony Pictures"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/pzKsRuKLFmYrW5Q0q8E8G78Tcgo.jpg',
      myRating: 8.6,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'Woody Harrelson terrifying Cletus Kasady and the chaotic cathedral red symbiote carnage.',
    },
    {
      id: 'movie-venom-the-last-dance',
      slug: 'venom-the-last-dance',
      type: 'movie',
      title: 'Venom: The Last Dance',
      releaseYear: 2024,
      genresJson: '["Action","Sci-Fi","Adventure"]',
      creatorsJson: '["Kelly Marcel","Sony Pictures"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/vGXptEdgZIhPg3cGlc7e8sNPC2e.jpg',
      myRating: 8.7,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        'Emotional road-trip finale to Eddie and Venom bond featuring Knull alien hordes and the Venom-horse.',
    },
    {
      id: 'movie-watchmen',
      slug: 'watchmen',
      type: 'movie',
      title: 'Watchmen',
      releaseYear: 2009,
      genresJson: '["Action","Drama","Mystery","Sci-Fi"]',
      creatorsJson: '["Zack Snyder"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/aVURelN3pM56lFM7Dgfs5TixcIf.jpg',
      myRating: 9.4,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'The opening Bob Dylan Times They Are A-Changin montage is the single greatest credit sequence in comic book history.',
    },
    {
      id: 'movie-whiplash',
      slug: 'whiplash',
      type: 'movie',
      title: 'Whiplash',
      releaseYear: 2014,
      genresJson: '["Drama","Music"]',
      creatorsJson: '["Damien Chazelle"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg',
      myRating: 9.7,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'Not quite my tempo. J.K. Simmons Fletcher psychological warfare and Miles Teller Caravan finale drum solo.',
    },
    {
      id: 'movie-wonder-woman',
      slug: 'wonder-woman',
      type: 'movie',
      title: 'Wonder Woman',
      releaseYear: 2017,
      genresJson: '["Action","Adventure","Fantasy"]',
      creatorsJson: '["Patty Jenkins"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/v4ncgZjG2Zu8ZW5al1vIZTsSjqX.jpg',
      myRating: 9.3,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'No Man Land trench charge to Rupert Gregson-Williams score is one of the most triumphant superhero moments on screen.',
    },
    {
      id: 'movie-wonder-woman-1984',
      slug: 'wonder-woman-1984',
      type: 'movie',
      title: 'Wonder Woman 1984',
      releaseYear: 2020,
      genresJson: '["Action","Adventure","Fantasy"]',
      creatorsJson: '["Patty Jenkins"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg',
      myRating: 8.1,
      watchStatus: 'completed',
      tier: 'recommended',
      personalReview:
        '80s technicolor aesthetic with Pedro Pascal unhinged Maxwell Lord and the Golden Eagle armor flight.',
    },
    {
      id: 'movie-zack-snyders-justice-league',
      slug: 'zack-snyders-justice-league',
      type: 'movie',
      title: "Zack Snyder's Justice League",
      releaseYear: 2021,
      genresJson: '["Action","Adventure","Fantasy"]',
      creatorsJson: '["Zack Snyder"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg',
      myRating: 9.5,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'The definitive 4-hour mythic opera. The Flash rewinding time scene and Junkie XL score are transcendent.',
    },
    {
      id: 'movie-zootopia',
      slug: 'zootopia',
      type: 'movie',
      title: 'Zootopia',
      releaseYear: 2016,
      genresJson: '["Animation","Adventure","Comedy"]',
      creatorsJson: '["Byron Howard","Rich Moore","Walt Disney"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/hlK0e0wAQ3VLuJcsfIYPvb4JVud.jpg',
      myRating: 9.4,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Sharp social commentary disguised as an animal buddy-cop noir. Flash the sloth at the DMV is comedy perfection.',
    },
    {
      id: 'movie-zootopia-2',
      slug: 'zootopia-2',
      type: 'movie',
      title: 'Zootopia 2',
      releaseYear: 2025,
      genresJson: '["Animation","Adventure","Comedy"]',
      creatorsJson: '["Byron Howard","Walt Disney"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/oJ7g2CifqpStmoYQyaLQgEU32qO.jpg',
      myRating: 9.2,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Judy Hopps and Nick Wilde investigating new reptile and semi-aquatic districts in the sprawling metropolis.',
    },
    {
      id: 'series-dark',
      slug: 'dark',
      type: 'tv_series',
      title: 'Dark',
      releaseYear: 2017,
      genresJson: '["Crime","Drama","Mystery","Sci-Fi"]',
      creatorsJson: '["Baran bo Odar","Jantje Friese"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/apbrbWs8M9lyOpJYU5WXrpFbk1Z.jpg',
      myRating: 9.9,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'The pinnacle of complex deterministic time travel. Winden nuclear town, the ouroboros knot, and the haunting realization that everything is connected.',
    },
    {
      id: 'series-game-of-thrones',
      slug: 'game-of-thrones',
      type: 'tv_series',
      title: 'Game of Thrones',
      releaseYear: 2011,
      genresJson: '["Fantasy","Drama","Political Intrigue"]',
      creatorsJson: '["David Benioff","D.B. Weiss","George R.R. Martin"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg',
      myRating: 9.7,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'Seasons 1-6 are the absolute peak of television history. The Red Wedding, Hardhome, and Battle of the Bastards are unmatched.',
    },
    {
      id: 'series-gram-chikitsalaya',
      slug: 'gram-chikitsalaya',
      type: 'tv_series',
      title: 'Gram Chikitsalaya',
      releaseYear: 2025,
      genresJson: '["Comedy","Drama","Slice of Life"]',
      creatorsJson:
        '["The Viral Fever (TVF)","Deepak Kumar Mishra","Arunabh Kumar"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/peRHZYhvuA6MLTJkpf5nIjgsWx5.jpg',
      myRating: 9.4,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Dr. Prabhat Sinha navigating rural healthcare challenges, quack rivalry, and heartfelt village community dynamics in classic TVF perfection.',
    },
    {
      id: 'series-house-of-the-dragon',
      slug: 'house-of-the-dragon',
      type: 'tv_series',
      title: 'House of the Dragon',
      releaseYear: 2022,
      genresJson: '["Action","Adventure","Drama","Fantasy"]',
      creatorsJson: '["Ryan J. Condal","George R.R. Martin","HBO"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/7V0Ebks0GgpKvQ7QbLAIdX5dos4.jpg',
      myRating: 9.5,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'Paddy Considine King Viserys walk to the Iron Throne and the brutal Dance of the Dragons Targaryen civil war.',
    },
    {
      id: 'series-light-shop',
      slug: 'light-shop',
      type: 'tv_series',
      title: 'Light Shop',
      releaseYear: 2024,
      genresJson: '["Drama","Fantasy","Mystery"]',
      creatorsJson: '["Kang Full","Disney+"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/iRgH73xibpeNZ8zzPDkIpxuoKgC.jpg',
      myRating: 9.3,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Kang Full deeply moving supernatural mystery where a luminescent lamp shop stands at the crossroads between life and the afterlife.',
    },
    {
      id: 'series-loki',
      slug: 'loki',
      type: 'tv_series',
      title: 'Loki',
      releaseYear: 2021,
      genresJson: '["Action","Adventure","Fantasy","Sci-Fi"]',
      creatorsJson: '["Michael Waldron","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/kEl2t3OhXc3Zb9FBh1AuYzRTgZp.jpg',
      myRating: 9.6,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'Tom Hiddleston God of Stories glorious purpose. Natalie Holt theremin score and the tragic temporal loom sacrifice.',
    },
    {
      id: 'series-mirzapur',
      slug: 'mirzapur',
      type: 'tv_series',
      title: 'Mirzapur',
      releaseYear: 2018,
      genresJson: '["Action","Crime","Thriller"]',
      creatorsJson: '["Karan Anshuman","Puneet Krishna"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/1rxLUFVrtTo82OxhbDXJDiJVkwL.jpg',
      myRating: 9.3,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Pankaj Tripathi as Akhandanand Tripathi (Kaleen Bhaiya) delivers iconic deadpan dominance. Raw power politics of Purvanchal.',
    },
    {
      id: 'series-monarch-legacy-of-monsters',
      slug: 'monarch-legacy-of-monsters',
      type: 'tv_series',
      title: 'Monarch: Legacy of Monsters',
      releaseYear: 2023,
      genresJson: '["Action","Adventure","Sci-Fi"]',
      creatorsJson: '["Chris Black","Matt Fraction","Legendary Television"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/7LBbaEaLSbqdviBYaSS1rRPMnrs.jpg',
      myRating: 9.3,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Kurt Russell and Wyatt Russell sharing the Lee Shaw character across dual timelines. Ground-level human drama anchored by terrifying Titan scale.',
    },
    {
      id: 'series-money-heist',
      slug: 'money-heist',
      type: 'tv_series',
      title: 'Money Heist (La Casa de Papel)',
      releaseYear: 2017,
      genresJson: '["Crime","Drama","Thriller","Heist"]',
      creatorsJson: '["\u00c1lex Pina"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg',
      myRating: 9.4,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'The Professor calculated chess match against inspector Murillo and Sierra. Bella Ciao rebellion anthem and brilliant psychological tension.',
    },
    {
      id: 'series-mr-robot',
      slug: 'mr-robot',
      type: 'tv_series',
      title: 'Mr. Robot',
      releaseYear: 2015,
      genresJson: '["Crime","Drama","Thriller"]',
      creatorsJson: '["Sam Esmail"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/kv1nRqgebSsREnd7vdC2pSGjpLo.jpg',
      myRating: 9.8,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'Rami Malek masterclass in dissociative identity and cyber-anarchy. Season 4 Episode 7 (Proxy Authentication Required) is peak television.',
    },
    {
      id: 'series-panchayat',
      slug: 'panchayat',
      type: 'tv_series',
      title: 'Panchayat',
      releaseYear: 2020,
      genresJson: '["Comedy","Drama","Slice of Life"]',
      creatorsJson: '["The Viral Fever (TVF)","Deepak Kumar Mishra"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/xrfvAhrMdT6Uwg5fyTyQAZBYyiu.jpg',
      myRating: 9.8,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'Phulera is pure warmth and authentic Indian rural reality. Jitendra Kumar, Neena Gupta, Raghubir Yadav, and Chandan Roy give heartfelt performances.',
    },
    {
      id: 'series-severance',
      slug: 'severance',
      type: 'tv_series',
      title: 'Severance',
      releaseYear: 2022,
      genresJson: '["Drama","Mystery","Sci-Fi","Thriller"]',
      creatorsJson: '["Dan Erickson","Ben Stiller"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/pPHpeI2X1qEd1CS1SeyrdhZ4qnT.jpg',
      myRating: 9.7,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'Lumon Industries surgically bifurcated minds. The Music Dance Experience, defiant waffle party, and the breathlessly tense season 1 finale.',
    },
    {
      id: 'series-silicon-valley',
      slug: 'silicon-valley',
      type: 'tv_series',
      title: 'Silicon Valley',
      releaseYear: 2014,
      genresJson: '["Comedy"]',
      creatorsJson: '["Mike Judge","John Altschuler","Dave Krinsky"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/4ptpmWBVD9HY9hMh8Cbs6SMiy7p.jpg',
      myRating: 9.5,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'The most ruthlessly accurate satire of tech startup culture ever created. Middle-out compression algorithm presentation was comedy gold.',
    },
    {
      id: 'series-succession',
      slug: 'succession',
      type: 'tv_series',
      title: 'Succession',
      releaseYear: 2018,
      genresJson: '["Drama"]',
      creatorsJson: '["Jesse Armstrong"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/z0XiwdrCQ9yVIr4O0pxzaAYRxdW.jpg',
      myRating: 9.8,
      watchStatus: 'completed',
      tier: 'masterpiece',
      personalReview:
        'Shakespearean corporate tragedy with venomous wit. Brian Cox Logan Roy shadow looms over Kendall, Shiv, and Roman generational trauma.',
    },
    {
      id: 'series-what-if',
      slug: 'what-if',
      type: 'tv_series',
      title: 'What If...?',
      releaseYear: 2021,
      genresJson: '["Animation","Action","Adventure","Sci-Fi"]',
      creatorsJson: '["A.C. Bradley","Marvel Studios"]',
      posterUrl:
        'https://image.tmdb.org/t/p/w500/lztz5XBMG1x6Y5ubz7CxfPFsAcW.jpg',
      myRating: 9.1,
      watchStatus: 'completed',
      tier: 'favorite',
      personalReview:
        'Jeffrey Wright The Watcher guiding us through tragic alternate realities, especially the heart-wrenching Doctor Strange Supreme episode.',
    },
  ];

  for (const item of entries) {
    await db
      .insert(schema.mediaEntry)
      .values({
        id: item.id,
        slug: item.slug,
        type: item.type,
        externalProvider: 'tmdb',
        externalId: null,
        title: item.title,
        releaseYear: item.releaseYear,
        genresJson: item.genresJson,
        creatorsJson: item.creatorsJson,
        posterUrl: item.posterUrl,
        backdropUrl: null,
        myRating: item.myRating,
        watchStatus: item.watchStatus,
        consumedAt: null,
        personalReview: item.personalReview,
        favoriteCharactersJson: JSON.stringify([]),
        favoriteScenesJson: JSON.stringify([]),
        quotesJson: JSON.stringify([]),
        tier: item.tier,
        galleryId: null,
        createdAt: now,
        updatedAt: now,
      })
      .onConflictDoUpdate({
        target: schema.mediaEntry.id,
        set: {
          title: item.title,
          type: item.type,
          releaseYear: item.releaseYear,
          genresJson: item.genresJson,
          creatorsJson: item.creatorsJson,
          posterUrl: item.posterUrl,
          myRating: item.myRating,
          personalReview: item.personalReview,
          tier: item.tier,
          updatedAt: now,
        },
      });
  }

  console.log('✅ Successfully seeded movies and webseries!');
}
