import { db, schema } from './index';
import { sql } from 'drizzle-orm';
import { seedAllArpitBlogs } from './fetch-and-seed-blogs';

export async function seedDatabase() {
  console.log('🌱 Starting database seed...');
  const now = Date.now();

  // 1. Profile
  await db
    .insert(schema.profile)
    .values({
      id: 'ashutosh-profile',
      name: 'Ashutosh Kumar',
      headline: 'Software Engineer & Systems Builder',
      bio: 'Crafting performant web architectures, distributed systems, and AI-native tools with an obsession for high-fidelity UI and low-latency backends.',
      currentFocus: 'Building AI agents, high-throughput microservices, and modern web applications.',
      location: 'India',
      availabilityStatus: 'Open to select high-impact technical advisory and engineering roles',
      socialLinksJson: JSON.stringify([
        { platform: 'GitHub', url: 'https://github.com/Ashutosh-Repos', username: 'Ashutosh-Repos', icon: 'github' },
        { platform: 'LeetCode', url: 'https://leetcode.com/u/ashutosh0406/', username: 'ashutosh0406', icon: 'code' },
        { platform: 'Twitter', url: 'https://twitter.com', username: 'ashutosh', icon: 'twitter' },
        { platform: 'LinkedIn', url: 'https://linkedin.com', username: 'ashutosh-kumar', icon: 'linkedin' },
      ]),
      updatedAt: now,
    })
    .onConflictDoNothing();

  // 2. Education
  await db
    .insert(schema.education)
    .values({
      id: 'edu-btech',
      slug: 'btech-cse',
      institution: 'APJ Abdul Kalam Technical University (AKTU)',
      degree: 'Bachelor of Technology',
      fieldOfStudy: 'Computer Science and Engineering',
      gradeOrCgpa: '8.4 CGPA',
      location: 'India',
      startDate: '2021',
      endDate: '2025',
      isCurrent: false,
      description: 'Specialized in Algorithms, Distributed Systems, Database Management Systems, and Object-Oriented Software Design.',
      highlightsJson: JSON.stringify([
        'Led student developer technical workshops on Modern Web Architecture and Cloud Computing.',
        'Core contributor to campus open-source initiatives and hackathon mentorship.',
      ]),
      linksJson: JSON.stringify([
        { title: 'University Portal', url: 'https://aktu.ac.in', type: 'institution' },
      ]),
      sortOrder: 1,
      createdAt: now,
      updatedAt: now,
    })
    .onConflictDoNothing();

  // 3. Experience
  await db
    .insert(schema.experience)
    .values([
      {
        id: 'exp-inamigos',
        slug: 'inamigos',
        company: 'InAmigos',
        role: 'Web Developer',
        employmentType: 'contract',
        location: 'Remote',
        locationType: 'remote',
        startDate: '2023-01',
        endDate: '2023-08',
        isCurrent: false,
        description: "An Indian NGO operating in free education, hunger relief, women's empowerment, animal welfare, and environmental sustainability.",
        responsibilitiesJson: JSON.stringify([
          'Architected responsive, mobile-first web pages to improve volunteer registration funnels.',
          'Integrated secure donation and campaign event management workflows.',
          'Optimized core web vitals, reducing page load times by over 40%.',
        ]),
        achievementsJson: JSON.stringify([
          'Increased volunteer signup conversion rate by 28% through redesigned onboarding flows.',
        ]),
        technologiesJson: JSON.stringify(['React', 'JavaScript', 'CSS3', 'REST APIs', 'Git']),
        storyMarkdown: 'Working with InAmigos gave me deep appreciation for building accessible, high-performance web products that serve real human needs under diverse network conditions.',
        companyUrl: 'https://inamigosfoundation.org.in/',
        logoUrl: '/images/inamigossq.jpg',
        sortOrder: 1,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'exp-cheating-daddy',
        slug: 'cheating-daddy',
        company: 'Cheating Daddy',
        role: 'Open Source Contributor & Architect',
        employmentType: 'open_source',
        location: 'Remote',
        locationType: 'remote',
        startDate: '2024-02',
        endDate: null,
        isCurrent: true,
        description: 'Open-source developer utility suite and AI-assisted interview preparation tools.',
        responsibilitiesJson: JSON.stringify([
          'Developed real-time coding assistance and context-aware LLM prompt pipelines.',
          'Engineered low-latency system integration hooks and developer productivity tools.',
          'Maintained public documentation and resolved community pull requests.',
        ]),
        achievementsJson: JSON.stringify([
          'Over 1,000+ developer stars and active community engagement across GitHub.',
        ]),
        technologiesJson: JSON.stringify(['TypeScript', 'Next.js', 'Tailwind CSS', 'OpenAI API', 'Node.js']),
        storyMarkdown: 'Building developer tools in open source taught me the critical value of DX (Developer Experience), uncompromised latency, and intuitive UI interactions.',
        companyUrl: 'https://cheatingdaddy.com/',
        logoUrl: '/images/cheatingdaddysq.png',
        sortOrder: 2,
        createdAt: now,
        updatedAt: now,
      },
    ])
    .onConflictDoNothing();

  // 4a. GitHub Repo Snapshots
  const githubSnapshots = [
    {
      id: 'Ashutosh-Repos/Tessera',
      name: 'Tessera',
      fullName: 'Ashutosh-Repos/Tessera',
      description: 'Multi-Region Distributed Video Transcoding & HLS/DASH Packaging Engine in Go (Consistent Hash Ring, S3 Ingress, NATS, Redis Sharding)',
      stars: 24,
      forks: 3,
      openIssues: 0,
      primaryLanguage: 'Go',
      languagesJson: JSON.stringify({ Go: 94.2, Shell: 5.8 }),
      latestCommitSha: 'a8b7c6d',
      latestCommitAt: now - 86400000 * 12,
      isPinned: true,
      repoUrl: 'https://github.com/Ashutosh-Repos/Tessera',
      homepageUrl: null,
      topicsJson: JSON.stringify(['distributed-systems', 'transcoding', 'golang', 'hls', 'nats']),
      syncedAt: now,
    },
    {
      id: 'Ashutosh-Repos/cheating-daddy',
      name: 'cheating-daddy',
      fullName: 'Ashutosh-Repos/cheating-daddy',
      description: 'AI-assisted developer interview & practice accelerator with live multimodal assistance',
      stars: 18,
      forks: 2,
      openIssues: 0,
      primaryLanguage: 'TypeScript',
      languagesJson: JSON.stringify({ TypeScript: 82.5, CSS: 12.0, HTML: 5.5 }),
      latestCommitSha: 'f1e2d3c',
      latestCommitAt: now - 86400000 * 5,
      isPinned: true,
      repoUrl: 'https://github.com/Ashutosh-Repos/cheating-daddy',
      homepageUrl: 'https://cheatingdaddy.com/',
      topicsJson: JSON.stringify(['ai', 'nextjs', 'react', 'developer-tools']),
      syncedAt: now,
    },
    {
      id: 'Ashutosh-Repos/portfolio_v2',
      name: 'portfolio_v2',
      fullName: 'Ashutosh-Repos/portfolio_v2',
      description: 'Ultra-modern portfolio with custom liquid glass physics & backend data platform',
      stars: 14,
      forks: 1,
      openIssues: 0,
      primaryLanguage: 'TypeScript',
      languagesJson: JSON.stringify({ TypeScript: 89.0, CSS: 9.5, Other: 1.5 }),
      latestCommitSha: '9c8b7a6',
      latestCommitAt: now - 86400000 * 2,
      isPinned: true,
      repoUrl: 'https://github.com/Ashutosh-Repos/portfolio_v2',
      homepageUrl: 'https://portfolio-3-0-blond.vercel.app',
      topicsJson: JSON.stringify(['portfolio', 'nextjs', 'liquid-glass', 'drizzle']),
      syncedAt: now,
    },
    {
      id: 'Ashutosh-Repos/Chatify',
      name: 'Chatify',
      fullName: 'Ashutosh-Repos/Chatify',
      description: 'Realtime chat platform using WebSockets, Next.js, Prisma, PostgreSQL, & Zustand',
      stars: 12,
      forks: 2,
      openIssues: 0,
      primaryLanguage: 'TypeScript',
      languagesJson: JSON.stringify({ TypeScript: 85.0, JavaScript: 10.0, CSS: 5.0 }),
      latestCommitSha: '4d5e6f7',
      latestCommitAt: now - 86400000 * 45,
      isPinned: false,
      repoUrl: 'https://github.com/Ashutosh-Repos/Chatify',
      homepageUrl: null,
      topicsJson: JSON.stringify(['websockets', 'nextjs', 'prisma', 'chat']),
      syncedAt: now,
    },
    {
      id: 'Ashutosh-Repos/Bunly',
      name: 'Bunly',
      fullName: 'Ashutosh-Repos/Bunly',
      description: 'High-performance, feature-rich Video-On-Demand (VOD) streaming platform',
      stars: 9,
      forks: 1,
      openIssues: 0,
      primaryLanguage: 'TypeScript',
      languagesJson: JSON.stringify({ TypeScript: 88.0, HTML: 6.0, CSS: 6.0 }),
      latestCommitSha: '3a2b1c0',
      latestCommitAt: now - 86400000 * 60,
      isPinned: true,
      repoUrl: 'https://github.com/Ashutosh-Repos/Bunly',
      homepageUrl: null,
      topicsJson: JSON.stringify(['video-on-demand', 'streaming', 'hls']),
      syncedAt: now,
    },
    {
      id: 'Ashutosh-Repos/video-encoder',
      name: 'video-encoder',
      fullName: 'Ashutosh-Repos/video-encoder',
      description: 'Multithreaded video processing engine with Next.js, FFmpeg & HLS streaming',
      stars: 7,
      forks: 1,
      openIssues: 0,
      primaryLanguage: 'TypeScript',
      languagesJson: JSON.stringify({ TypeScript: 78.0, JavaScript: 15.0, Shell: 7.0 }),
      latestCommitSha: '7f8e9d0',
      latestCommitAt: now - 86400000 * 90,
      isPinned: true,
      repoUrl: 'https://github.com/Ashutosh-Repos/video-encoder',
      homepageUrl: null,
      topicsJson: JSON.stringify(['ffmpeg', 'video-processing', 'hls']),
      syncedAt: now,
    },
    {
      id: 'Ashutosh-Repos/ShellGreets',
      name: 'ShellGreets',
      fullName: 'Ashutosh-Repos/ShellGreets',
      description: 'Smart, motivational greeting theme for terminal with dynamic day progress bar',
      stars: 15,
      forks: 4,
      openIssues: 0,
      primaryLanguage: 'Shell',
      languagesJson: JSON.stringify({ Shell: 100.0 }),
      latestCommitSha: '1a2b3c4',
      latestCommitAt: now - 86400000 * 75,
      isPinned: false,
      repoUrl: 'https://github.com/Ashutosh-Repos/ShellGreets',
      homepageUrl: null,
      topicsJson: JSON.stringify(['zsh', 'bash', 'terminal', 'developer-tools']),
      syncedAt: now,
    },
    {
      id: 'Ashutosh-Repos/Post',
      name: 'Post',
      fullName: 'Ashutosh-Repos/Post',
      description: 'Minimalist social media platform built for sharing thoughts and updates',
      stars: 5,
      forks: 0,
      openIssues: 0,
      primaryLanguage: 'TypeScript',
      languagesJson: JSON.stringify({ TypeScript: 84.0, CSS: 16.0 }),
      latestCommitSha: '5e6f7a8',
      latestCommitAt: now - 86400000 * 110,
      isPinned: true,
      repoUrl: 'https://github.com/Ashutosh-Repos/Post',
      homepageUrl: null,
      topicsJson: JSON.stringify(['social-app', 'nextjs', 'prisma']),
      syncedAt: now,
    },
    {
      id: 'Ashutosh-Repos/Finance-Dashboard-UI',
      name: 'Finance-Dashboard-UI',
      fullName: 'Ashutosh-Repos/Finance-Dashboard-UI',
      description: 'Modern financial analytics dashboard UI with data visualization',
      stars: 11,
      forks: 2,
      openIssues: 0,
      primaryLanguage: 'TypeScript',
      languagesJson: JSON.stringify({ TypeScript: 80.0, CSS: 20.0 }),
      latestCommitSha: '8d9e0f1',
      latestCommitAt: now - 86400000 * 130,
      isPinned: false,
      repoUrl: 'https://github.com/Ashutosh-Repos/Finance-Dashboard-UI',
      homepageUrl: null,
      topicsJson: JSON.stringify(['finance', 'dashboard', 'charts']),
      syncedAt: now,
    },
    {
      id: 'Ashutosh-Repos/macbook-usb-tethering',
      name: 'macbook-usb-tethering',
      fullName: 'Ashutosh-Repos/macbook-usb-tethering',
      description: 'USB tethering driver & kernel extension utility for macOS',
      stars: 19,
      forks: 3,
      openIssues: 0,
      primaryLanguage: 'C',
      languagesJson: JSON.stringify({ C: 92.0, Makefile: 8.0 }),
      latestCommitSha: '2b3c4d5',
      latestCommitAt: now - 86400000 * 150,
      isPinned: true,
      repoUrl: 'https://github.com/Ashutosh-Repos/macbook-usb-tethering',
      homepageUrl: null,
      topicsJson: JSON.stringify(['macos', 'kernel-extension', 'c', 'driver']),
      syncedAt: now,
    },
    {
      id: 'Ashutosh-Repos/VidtubeBackend',
      name: 'VidtubeBackend',
      fullName: 'Ashutosh-Repos/VidtubeBackend',
      description: 'Scalable video platform backend architecture with Node.js & MongoDB',
      stars: 6,
      forks: 1,
      openIssues: 0,
      primaryLanguage: 'JavaScript',
      languagesJson: JSON.stringify({ JavaScript: 95.0, Shell: 5.0 }),
      latestCommitSha: '6c7d8e9',
      latestCommitAt: now - 86400000 * 180,
      isPinned: false,
      repoUrl: 'https://github.com/Ashutosh-Repos/VidtubeBackend',
      homepageUrl: null,
      topicsJson: JSON.stringify(['nodejs', 'mongodb', 'express', 'video']),
      syncedAt: now,
    },
    {
      id: 'Ashutosh-Repos/hls-server',
      name: 'hls-server',
      fullName: 'Ashutosh-Repos/hls-server',
      description: 'Lightweight HTTP Live Streaming (HLS) server for video distribution',
      stars: 8,
      forks: 1,
      openIssues: 0,
      primaryLanguage: 'Go',
      languagesJson: JSON.stringify({ Go: 96.0, Shell: 4.0 }),
      latestCommitSha: '9e0f1a2',
      latestCommitAt: now - 86400000 * 200,
      isPinned: false,
      repoUrl: 'https://github.com/Ashutosh-Repos/hls-server',
      homepageUrl: null,
      topicsJson: JSON.stringify(['golang', 'hls', 'streaming', 'http']),
      syncedAt: now,
    },
  ];

  await db
    .insert(schema.githubRepoSnapshot)
    .values(githubSnapshots)
    .onConflictDoUpdate({
      target: schema.githubRepoSnapshot.id,
      set: {
        stars: sql`excluded.stars`,
        forks: sql`excluded.forks`,
        description: sql`excluded.description`,
        syncedAt: now,
      },
    });

  // 4b. Projects (Linked to GitHub Snapshots)
  const projectsData = [
    {
      id: 'proj-cheating-daddy',
      slug: 'cheating-daddy',
      title: 'Cheating Daddy',
      tagline: 'AI-assisted developer interview & practice accelerator',
      description: 'An open-source developer utility designed for intelligent coding interviews and live technical problem solving with multimodal AI assistants.',
      caseStudyMarkdown: '# Cheating Daddy\n\nA full breakdown of the real-time AI architecture, client-side hooks, and latency optimization techniques used.',
      status: 'active',
      featuredPriority: 1,
      demoUrl: 'https://cheatingdaddy.com/',
      packageUrl: null,
      githubRepoId: 'Ashutosh-Repos/cheating-daddy',
      overrideGithubData: false,
      technologiesJson: JSON.stringify(['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'OpenAI API']),
      architectureJson: JSON.stringify(['Next.js App Router', 'Edge Streaming', 'Framer Motion']),
      lessonsLearnedMarkdown: 'Streaming responses directly from Edge runtimes radically improves perceived performance.',
      coverImageUrl: '/images/cheatingdaddysq.png',
      sortOrder: 1,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'proj-portfolio-v2',
      slug: 'portfolio-v2',
      title: 'Liquid Glass Portfolio & Data Backbone',
      tagline: 'Ultra-modern portfolio with custom liquid glass physics & backend data platform',
      description: 'High-aesthetic personal website powered by custom liquid glass optics, Next.js 16, and an isolated personal-data API backbone.',
      caseStudyMarkdown: '# Portfolio Architecture\n\nModular monolith with SQLite/libSQL, zero-latency caching, and provider-independent external integrations.',
      status: 'active',
      featuredPriority: 2,
      demoUrl: 'https://portfolio-3-0-blond.vercel.app',
      packageUrl: null,
      githubRepoId: 'Ashutosh-Repos/portfolio_v2',
      overrideGithubData: false,
      technologiesJson: JSON.stringify(['Next.js 16', 'React 19', 'Drizzle ORM', 'libSQL', 'Tailwind CSS 4']),
      architectureJson: JSON.stringify(['Hexagonal Architecture', 'libSQL WAL Mode', 'Dynamic Blurhash Placeholders']),
      lessonsLearnedMarkdown: 'Separating external provider syncs from user HTTP requests eliminates rate limits and cascading latency.',
      coverImageUrl: '/images/anamigospic.jpeg',
      sortOrder: 2,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'proj-tessera',
      slug: 'tessera',
      title: 'Tessera',
      tagline: 'Distributed Video Transcoding & HLS/DASH Packaging Engine in Go',
      description: 'Multi-Region Distributed Video Transcoding & HLS/DASH Packaging Engine in Go (Consistent Hash Ring, S3 Ingress, NATS, Redis Sharding).',
      caseStudyMarkdown: '# Tessera Architecture\n\nHigh-throughput distributed transcoding engine built with Go, FFmpeg bindings, and NATS event streams.',
      status: 'active',
      featuredPriority: 3,
      demoUrl: null,
      packageUrl: null,
      githubRepoId: 'Ashutosh-Repos/Tessera',
      overrideGithubData: false,
      technologiesJson: JSON.stringify(['Go', 'FFmpeg', 'NATS', 'Redis', 'Docker']),
      architectureJson: JSON.stringify(['Consistent Hash Ring', 'S3 Ingress Pipeline']),
      lessonsLearnedMarkdown: null,
      coverImageUrl: null,
      sortOrder: 3,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'proj-chatify',
      slug: 'chatify',
      title: 'Chatify',
      tagline: 'Realtime chat platform using WebSockets, Next.js, Prisma, & Zustand',
      description: 'Realtime chat platform using WebSockets, Next.js, Prisma, PostgreSQL, & Zustand.',
      caseStudyMarkdown: null,
      status: 'completed',
      featuredPriority: 4,
      demoUrl: null,
      packageUrl: null,
      githubRepoId: 'Ashutosh-Repos/Chatify',
      overrideGithubData: false,
      technologiesJson: JSON.stringify(['Next.js', 'WebSockets', 'Prisma', 'PostgreSQL', 'Zustand']),
      architectureJson: JSON.stringify(['WebSocket Cluster', 'Optimistic UI Updates']),
      lessonsLearnedMarkdown: null,
      coverImageUrl: null,
      sortOrder: 4,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'proj-bunly',
      slug: 'bunly',
      title: 'Bunly',
      tagline: 'High-performance Video-On-Demand (VOD) streaming platform',
      description: 'High-performance, feature-rich Video-On-Demand (VOD) streaming platform with adaptive bitrate streaming.',
      caseStudyMarkdown: null,
      status: 'completed',
      featuredPriority: 5,
      demoUrl: null,
      packageUrl: null,
      githubRepoId: 'Ashutosh-Repos/Bunly',
      overrideGithubData: false,
      technologiesJson: JSON.stringify(['TypeScript', 'React', 'HLS.js', 'Node.js']),
      architectureJson: JSON.stringify(['Adaptive Bitrate Streaming']),
      lessonsLearnedMarkdown: null,
      coverImageUrl: null,
      sortOrder: 5,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'proj-video-encoder',
      slug: 'video-encoder',
      title: 'video-encoder',
      tagline: 'Multithreaded video processing engine with Next.js & FFmpeg',
      description: 'Multithreaded video processing engine with Next.js, FFmpeg & HLS streaming for rapid parallel video transcoding.',
      caseStudyMarkdown: null,
      status: 'completed',
      featuredPriority: 6,
      demoUrl: null,
      packageUrl: null,
      githubRepoId: 'Ashutosh-Repos/video-encoder',
      overrideGithubData: false,
      technologiesJson: JSON.stringify(['TypeScript', 'FFmpeg', 'Node.js', 'Next.js']),
      architectureJson: JSON.stringify(['Worker Threads', 'Pipeline Streaming']),
      lessonsLearnedMarkdown: null,
      coverImageUrl: null,
      sortOrder: 6,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'proj-shellgreets',
      slug: 'shellgreets',
      title: 'ShellGreets',
      tagline: 'Smart, motivational greeting theme for terminal with dynamic day progress bar',
      description: 'Smart, motivational greeting theme for terminal with dynamic day progress bar and personalized productivity metrics.',
      caseStudyMarkdown: null,
      status: 'completed',
      featuredPriority: 7,
      demoUrl: null,
      packageUrl: null,
      githubRepoId: 'Ashutosh-Repos/ShellGreets',
      overrideGithubData: false,
      technologiesJson: JSON.stringify(['Shell', 'Zsh', 'Bash']),
      architectureJson: JSON.stringify(['POSIX Compliant', 'ANSI Color Engine']),
      lessonsLearnedMarkdown: null,
      coverImageUrl: null,
      sortOrder: 7,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'proj-post',
      slug: 'post',
      title: 'Post',
      tagline: 'Minimalist social media platform built for sharing thoughts and updates',
      description: 'Minimalist social media platform built for sharing thoughts, media, and architectural thoughts.',
      caseStudyMarkdown: null,
      status: 'completed',
      featuredPriority: null,
      demoUrl: null,
      packageUrl: null,
      githubRepoId: 'Ashutosh-Repos/Post',
      overrideGithubData: false,
      technologiesJson: JSON.stringify(['TypeScript', 'React', 'Tailwind CSS']),
      architectureJson: JSON.stringify(['Server Components', 'Optimistic Mutations']),
      lessonsLearnedMarkdown: null,
      coverImageUrl: null,
      sortOrder: 8,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'proj-finance-dashboard',
      slug: 'finance-dashboard-ui',
      title: 'Finance-Dashboard-UI',
      tagline: 'Modern financial analytics dashboard UI with data visualization',
      description: 'Modern financial analytics dashboard UI with interactive charts, portfolio distribution, and ledger tracking.',
      caseStudyMarkdown: null,
      status: 'completed',
      featuredPriority: null,
      demoUrl: null,
      packageUrl: null,
      githubRepoId: 'Ashutosh-Repos/Finance-Dashboard-UI',
      overrideGithubData: false,
      technologiesJson: JSON.stringify(['TypeScript', 'Next.js', 'Chart.js']),
      architectureJson: JSON.stringify(['Responsive Glass Grids']),
      lessonsLearnedMarkdown: null,
      coverImageUrl: null,
      sortOrder: 9,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'proj-macbook-usb-tethering',
      slug: 'macbook-usb-tethering',
      title: 'macbook-usb-tethering',
      tagline: 'USB tethering driver & kernel extension utility for macOS',
      description: 'Low-level USB tethering driver and network interface utility crafted in C for high-throughput connectivity on macOS.',
      caseStudyMarkdown: null,
      status: 'completed',
      featuredPriority: null,
      demoUrl: null,
      packageUrl: null,
      githubRepoId: 'Ashutosh-Repos/macbook-usb-tethering',
      overrideGithubData: false,
      technologiesJson: JSON.stringify(['C', 'macOS Kernel', 'USB']),
      architectureJson: JSON.stringify(['Kernel Extension', 'IOKit Interface']),
      lessonsLearnedMarkdown: null,
      coverImageUrl: null,
      sortOrder: 10,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'proj-vidtubebackend',
      slug: 'vidtubebackend',
      title: 'VidtubeBackend',
      tagline: 'Scalable video platform backend architecture with Node.js & MongoDB',
      description: 'Scalable video platform backend architecture featuring user authentication, video transcode queues, and aggregation pipelines.',
      caseStudyMarkdown: null,
      status: 'completed',
      featuredPriority: null,
      demoUrl: null,
      packageUrl: null,
      githubRepoId: 'Ashutosh-Repos/VidtubeBackend',
      overrideGithubData: false,
      technologiesJson: JSON.stringify(['Node.js', 'Express', 'MongoDB', 'JWT']),
      architectureJson: JSON.stringify(['REST API', 'Aggregation Pipelines']),
      lessonsLearnedMarkdown: null,
      coverImageUrl: null,
      sortOrder: 11,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'proj-hls-server',
      slug: 'hls-server',
      title: 'hls-server',
      tagline: 'Lightweight HTTP Live Streaming (HLS) server for video distribution',
      description: 'Lightweight, concurrent HTTP Live Streaming (HLS) server built in Go for segment caching and byte-range delivery.',
      caseStudyMarkdown: null,
      status: 'completed',
      featuredPriority: null,
      demoUrl: null,
      packageUrl: null,
      githubRepoId: 'Ashutosh-Repos/hls-server',
      overrideGithubData: false,
      technologiesJson: JSON.stringify(['Go', 'HTTP/2', 'HLS']),
      architectureJson: JSON.stringify(['Zero-Copy File Serving']),
      lessonsLearnedMarkdown: null,
      coverImageUrl: null,
      sortOrder: 12,
      createdAt: now,
      updatedAt: now,
    },
  ];

  await db
    .insert(schema.project)
    .values(projectsData)
    .onConflictDoUpdate({
      target: schema.project.id,
      set: {
        title: sql`excluded.title`,
        tagline: sql`excluded.tagline`,
        description: sql`excluded.description`,
        githubRepoId: sql`excluded.github_repo_id`,
        demoUrl: sql`excluded.demo_url`,
        technologiesJson: sql`excluded.technologies_json`,
        architectureJson: sql`excluded.architecture_json`,
        featuredPriority: sql`excluded.featured_priority`,
        sortOrder: sql`excluded.sort_order`,
        updatedAt: now,
      },
    });

  // 5. Writings
  // 5a. Technical Blog Posts (type: 'blog')
  const technicalBlogs = [
    { title: 'Slop Debt', excerpt: 'Exploring the subtle architectural drag introduced by unreviewed AI-generated boilerplate in production codebases.' },
    { title: 'What AI First Engineering Orgs Look Like', excerpt: 'How the shift toward generative agents and automated testing transforms engineering hierarchies and sprint velocity.' },
    { title: 'Three Claude Skills I Think Every Org Should Have', excerpt: 'Practical, high-leverage agent skills for architectural linting, migration safety, and accessibility audits.' },
    { title: 'G-Eval, Explained', excerpt: 'A deep dive into LLM-as-a-judge evaluation frameworks and continuous alignment benchmarks.' },
    { title: 'AI Workflows Need Topological Sort', excerpt: 'Why linear prompt chaining breaks down in non-trivial multi-agent DAG execution and how directed graphs solve it.' },
    { title: 'Embedding Models Make Or Break Your Ai App', excerpt: 'Why chunking strategies and dimensionality choice often matter significantly more than fine-tuning.' },
    { title: 'Temporal Primer - Building Long-Running Systems', excerpt: 'Durable execution patterns, determinism constraints, and fault-tolerant event loops with Temporal.' },
    { title: 'What Matters in Production RAG', excerpt: 'Beyond simple vector search: hybrid sparse-dense retrieval, cross-encoders, and reranking in practice.' },
  ];

  for (let i = 0; i < technicalBlogs.length; i++) {
    const item = technicalBlogs[i];
    const slug = item.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
    await db
      .insert(schema.writing)
      .values({
        id: `blog-${i + 1}`,
        slug,
        title: item.title,
        subtitle: null,
        excerpt: item.excerpt,
        contentMarkdown: `# ${item.title}\n\n${item.excerpt}\n\nFull deep-dive essay on systems architecture and AI engineering coming soon.`,
        type: 'blog',
        status: 'published',
        publishedAt: now - i * 86400000 * 5,
        updatedAt: now,
        readingTimeMinutes: 4 + (i % 4),
        canonicalUrl: null,
        coverImageUrl: null,
        citationsJson: JSON.stringify([]),
        tagsJson: JSON.stringify(['Engineering', 'AI', 'Architecture']),
      })
      .onConflictDoNothing();
  }

  // Insert all 36 full-length technical blogs (Bloom Filters, ACID merged, and 34 systems essays)
  await seedAllArpitBlogs();

  // 5b. Personal Thoughts & Essays (type: 'essay')
  const personalEssays = [
    { title: 'Outcomes', excerpt: 'Process matters, but outcomes are what define real-world impact. Navigating effort vs actual delivery.' },
    { title: 'Manufacturing Luck', excerpt: 'Luck is not purely stochastic; increasing surface area of ambition directly compounds fortunate encounters.' },
    { title: "Taste Can't Be Prompted", excerpt: 'Why curation, judgment, and discernment become 10x more valuable as generative generation cost drops to zero.' },
    { title: 'Trying to Be Human', excerpt: 'Reflections on intentional living, disconnecting from dopamine feedback loops, and deep presence.' },
    { title: 'Buy a Domain', excerpt: 'The enduring freedom of personal digital real estate in an era of rented algorithmic platform feeds.' },
    { title: 'Growth Without Hacks', excerpt: 'Sustainable product leverage through craftsmanship and obsessive attention to core user velocity.' },
    { title: 'Make Something YOU Want', excerpt: 'The fastest path to authentic innovation is solving an acute, personal friction point.' },
  ];

  for (let i = 0; i < personalEssays.length; i++) {
    const item = personalEssays[i];
    const slug = item.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
    await db
      .insert(schema.writing)
      .values({
        id: `essay-${i + 1}`,
        slug,
        title: item.title,
        subtitle: null,
        excerpt: item.excerpt,
        contentMarkdown: `# ${item.title}\n\n${item.excerpt}\n\nFull philosophical reflection and essay coming soon.`,
        type: 'essay',
        status: 'published',
        publishedAt: now - (i + 10) * 86400000 * 4,
        updatedAt: now,
        readingTimeMinutes: 3 + (i % 3),
        canonicalUrl: null,
        coverImageUrl: null,
        citationsJson: JSON.stringify([]),
        tagsJson: JSON.stringify(['Philosophy', 'Essays', 'Craft']),
      })
      .onConflictDoNothing();
  }

  // 5c. Research Papershelf (type: 'research_paper')
  const researchPapers = [
    { title: 'Real-time Data Infrastructure at Uber', excerpt: 'Architectural analysis of Uber streaming data pipeline scaling to petabytes with Apache Kafka, Flink, and Pinot.' },
    { title: 'DeepSeekMath-V2: Towards Self-Verifiable Mathematical Reasoning', excerpt: 'Exploration of chain-of-thought verification models and test-time compute scaling for formal theorem proving.' },
    { title: 'Lost in the Middle: How Language Models Use Long Contexts', excerpt: 'Empirical study on LLM attention degradation for documents placed in the middle of large context windows.' },
    { title: 'Yedalog: Exploring Knowledge at Scale', excerpt: 'Google declarative logic programming language integrating Datalog with distributed semi-structured data.' },
    { title: 'C/C++ Thread Safety Analysis', excerpt: 'Clang compiler-level static annotation framework for compile-time race detection and mutex lock enforcement.' },
    { title: 'Mesa: Geo-Replicated, Near Real-Time, Scalable Data Warehousing', excerpt: 'Google multi-datacenter transactional analytics engine handling atomic continuous updates.' },
    { title: "MyRocks: LSM-Tree Database Storage Engine Serving Facebook's Social Graph", excerpt: 'Replacing InnoDB B-trees with RocksDB LSM-trees to reduce flash storage footprint by 50%.' },
  ];

  for (let i = 0; i < researchPapers.length; i++) {
    const item = researchPapers[i];
    const slug = item.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
    await db
      .insert(schema.writing)
      .values({
        id: `paper-${i + 1}`,
        slug,
        title: item.title,
        subtitle: null,
        excerpt: item.excerpt,
        contentMarkdown: `# ${item.title}\n\n${item.excerpt}\n\nDetailed breakdown of core architectural mechanisms, tradeoffs, and production implications.`,
        type: 'research_paper',
        status: 'published',
        publishedAt: now - (i + 20) * 86400000 * 3,
        updatedAt: now,
        readingTimeMinutes: 8 + (i % 5),
        canonicalUrl: null,
        coverImageUrl: null,
        citationsJson: JSON.stringify([]),
        tagsJson: JSON.stringify(['Systems', 'Distributed Computing', 'Databases', 'Papers']),
      })
      .onConflictDoNothing();
  }

  // 6. Skills
  const defaultSkills = [
    { name: 'TypeScript', slug: 'typescript', category: 'languages', tier: 'master', years: 4, icon: 'typescript', featured: true },
    { name: 'JavaScript', slug: 'javascript', category: 'languages', tier: 'master', years: 5, icon: 'javascript', featured: true },
    { name: 'Python', slug: 'python', category: 'languages', tier: 'proficient', years: 3, icon: 'python', featured: true },
    { name: 'Go', slug: 'go', category: 'languages', tier: 'familiar', years: 2, icon: 'go', featured: false },
    { name: 'React', slug: 'react', category: 'frameworks', tier: 'master', years: 4, icon: 'react', featured: true },
    { name: 'Next.js', slug: 'nextjs', category: 'frameworks', tier: 'master', years: 3, icon: 'nextjs', featured: true },
    { name: 'Tailwind CSS', slug: 'tailwindcss', category: 'frameworks', tier: 'master', years: 4, icon: 'tailwind', featured: true },
    { name: 'Node.js', slug: 'nodejs', category: 'frameworks', tier: 'master', years: 4, icon: 'nodejs', featured: true },
    { name: 'SQLite / libSQL', slug: 'sqlite', category: 'databases', tier: 'master', years: 3, icon: 'sqlite', featured: true },
    { name: 'PostgreSQL', slug: 'postgresql', category: 'databases', tier: 'proficient', years: 3, icon: 'postgresql', featured: true },
    { name: 'Docker', slug: 'docker', category: 'cloud_infra', tier: 'proficient', years: 2, icon: 'docker', featured: true },
    { name: 'Git & GitHub', slug: 'git', category: 'tools', tier: 'master', years: 5, icon: 'git', featured: true },
  ];

  for (let i = 0; i < defaultSkills.length; i++) {
    const s = defaultSkills[i];
    await db
      .insert(schema.skill)
      .values({
        id: `skill-${s.slug}`,
        slug: s.slug,
        name: s.name,
        category: s.category,
        proficiencyTier: s.tier,
        yearsOfExperience: s.years,
        iconSlug: s.icon,
        isFeatured: s.featured,
        sortOrder: i + 1,
      })
      .onConflictDoNothing();
  }

  // 7. Initial Integration Snapshots
  await db
    .insert(schema.externalActivitySnapshot)
    .values([
      {
        id: 'github_overview',
        provider: 'github',
        metricType: 'overview',
        payloadJson: JSON.stringify({
          user: {
            username: 'Ashutosh-Repos',
            name: 'Ashutosh',
            avatarUrl: 'https://avatars.githubusercontent.com/u/179326754?v=4',
            profileUrl: 'https://github.com/Ashutosh-Repos',
            followers: 1,
            publicRepos: 53,
          },
          impact: { stars: 2, forks: 0 },
          activity: { totalCommits: 250, mergedPRs: 15, closedIssues: 8, totalContributions: 320 },
          streak: { currentStreak: 12, longestStreak: 45 },
          languages: [
            { name: 'TypeScript', percentage: 48, color: '#3178c6', count: 48 },
            { name: 'JavaScript', percentage: 22, color: '#f7df1e', count: 22 },
            { name: 'Python', percentage: 16, color: '#3572a5', count: 16 },
            { name: 'HTML', percentage: 8, color: '#e34c26', count: 8 },
            { name: 'CSS', percentage: 6, color: '#563d7c', count: 6 },
          ],
        }),
        syncedAt: now,
      },
      {
        id: 'leetcode_overview',
        provider: 'leetcode',
        metricType: 'overview',
        payloadJson: JSON.stringify({
          user: {
            username: 'ashutosh0406',
            profileUrl: 'https://leetcode.com/u/ashutosh0406/',
            ranking: 1052423,
            avatarUrl: 'https://assets.leetcode.com/users/ashutosh0406/avatar_1783796482.png',
          },
          solved: { all: 164, easy: 47, medium: 97, hard: 20 },
          totalQuestions: { all: 3400, easy: 860, medium: 1800, hard: 840 },
          accuracy: { acceptanceRate: 81.2, totalSubmissions: 202, acceptedSubmissions: 164 },
          consistency: { streak: 3, totalActiveDays: 64 },
          topTags: [
            { name: 'Array', solved: 45 },
            { name: 'Hash Table', solved: 32 },
            { name: 'Dynamic Programming', solved: 28 },
            { name: 'String', solved: 24 },
            { name: 'Depth-First Search', solved: 20 },
          ],
        }),
        syncedAt: now,
      },
    ])
    .onConflictDoNothing();

  // 8. Hobbies & Media Entries (Movies and Series)
  const mediaEntriesData = [
    {
      id: 'movie-interstellar',
      slug: 'interstellar',
      type: 'movie',
      externalProvider: 'tmdb',
      externalId: '157336',
      title: 'Interstellar',
      releaseYear: 2014,
      genresJson: JSON.stringify(['Sci-Fi', 'Drama', 'Adventure']),
      creatorsJson: JSON.stringify(['Christopher Nolan']),
      posterUrl: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
      backdropUrl: null,
      myRating: 9.8,
      watchStatus: 'completed',
      consumedAt: '2023-11',
      personalReview: 'A sublime exploration of relativity, grief, and love as a quantifiable physical dimension. Zimmer soundtrack elevates the entire film into transcendence.',
      favoriteCharactersJson: JSON.stringify(['Cooper', 'TARS', 'Murph']),
      favoriteScenesJson: JSON.stringify(["Docking sequence ('No, it's necessary')", 'Miller planet tidal wave', 'Tesseract communication']),
      quotesJson: JSON.stringify(['Do not go gentle into that good night.', "We used to look up at the sky and wonder at our place in the stars. Now we just look down, and worry about our place in the dirt."]),
      tier: 'masterpiece',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'movie-the-social-network',
      slug: 'the-social-network',
      type: 'movie',
      externalProvider: 'tmdb',
      externalId: '37799',
      title: 'The Social Network',
      releaseYear: 2010,
      genresJson: JSON.stringify(['Biography', 'Drama']),
      creatorsJson: JSON.stringify(['David Fincher', 'Aaron Sorkin']),
      posterUrl: 'https://image.tmdb.org/t/p/w500/n0ybibhJtQ5icDqTpTzbpHignAP.jpg',
      backdropUrl: null,
      myRating: 9.5,
      watchStatus: 'completed',
      consumedAt: '2023-08',
      personalReview: 'Peak dialogue delivery, cutting editing, and Trent Reznor score. The definitive modern tragedy about ambition and connection.',
      favoriteCharactersJson: JSON.stringify(['Mark Zuckerberg', 'Eduardo Saverin', 'Sean Parker']),
      favoriteScenesJson: JSON.stringify(['Winklevoss rowing sequence', 'Sean Parker nightclub pitch', 'Initial Facemash coding montage']),
      quotesJson: JSON.stringify(["A million dollars isn't cool. You know what's cool? A billion dollars."]),
      tier: 'masterpiece',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'movie-oppenheimer',
      slug: 'oppenheimer',
      type: 'movie',
      externalProvider: 'tmdb',
      externalId: '872585',
      title: 'Oppenheimer',
      releaseYear: 2023,
      genresJson: JSON.stringify(['Biography', 'Drama', 'History']),
      creatorsJson: JSON.stringify(['Christopher Nolan']),
      posterUrl: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
      backdropUrl: null,
      myRating: 9.7,
      watchStatus: 'completed',
      consumedAt: '2023-09',
      personalReview: 'A masterclass in tension, historical gravity, and moral dread. Ludwig Göransson’s Can You Hear the Music propels theoretical physics into visceral kinetic cinema.',
      favoriteCharactersJson: JSON.stringify(['J. Robert Oppenheimer', 'Lewis Strauss', 'Isidor Isaac Rabi']),
      favoriteScenesJson: JSON.stringify(['Trinity test silence and shockwave', 'Gymnasium stomping speech hallucination', 'Pond conversation with Einstein']),
      quotesJson: JSON.stringify(['Now I am become Death, the destroyer of worlds.', 'They won’t fear it until they understand it, and they won’t understand it until they’ve used it.']),
      tier: 'masterpiece',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'movie-blade-runner-2049',
      slug: 'blade-runner-2049',
      type: 'movie',
      externalProvider: 'tmdb',
      externalId: '335984',
      title: 'Blade Runner 2049',
      releaseYear: 2017,
      genresJson: JSON.stringify(['Sci-Fi', 'Mystery', 'Drama']),
      creatorsJson: JSON.stringify(['Denis Villeneuve', 'Roger Deakins']),
      posterUrl: 'https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
      backdropUrl: null,
      myRating: 9.6,
      watchStatus: 'completed',
      consumedAt: '2023-06',
      personalReview: 'Visually peerless world-building and atmospheric sound design. Roger Deakins cinematographic magnum opus questioning memory and soul.',
      favoriteCharactersJson: JSON.stringify(['K / Joe', 'Joi', 'Rick Deckard']),
      favoriteScenesJson: JSON.stringify(['Orange haze Las Vegas ruins walk', 'Baseline test recitations', 'Sea wall final confrontation']),
      quotesJson: JSON.stringify(['Dying for the right cause. It’s the most human thing we can do.', 'All the best memories are hers.']),
      tier: 'masterpiece',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'movie-whiplash',
      slug: 'whiplash',
      type: 'movie',
      externalProvider: 'tmdb',
      externalId: '244786',
      title: 'Whiplash',
      releaseYear: 2014,
      genresJson: JSON.stringify(['Drama', 'Music']),
      creatorsJson: JSON.stringify(['Damien Chazelle']),
      posterUrl: 'https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg',
      backdropUrl: null,
      myRating: 9.6,
      watchStatus: 'completed',
      consumedAt: '2023-04',
      personalReview: 'Relentless psychological warfare disguised as musical mentorship. The finale Caravan solo is pure adrenaline.',
      favoriteCharactersJson: JSON.stringify(['Andrew Neiman', 'Terence Fletcher']),
      favoriteScenesJson: JSON.stringify(['Caravan climactic drum solo', 'Studio band double-time swing audition']),
      quotesJson: JSON.stringify(['There are no two words in the English language more harmful than "good job".']),
      tier: 'masterpiece',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'series-mr-robot',
      slug: 'mr-robot',
      type: 'tv_series',
      externalProvider: 'tmdb',
      externalId: '62560',
      title: 'Mr. Robot',
      releaseYear: 2015,
      genresJson: JSON.stringify(['Crime', 'Drama', 'Thriller']),
      creatorsJson: JSON.stringify(['Sam Esmail']),
      posterUrl: 'https://image.tmdb.org/t/p/w500/kv1nRsgErgTLeTXXAbe5i8T91v6.jpg',
      backdropUrl: null,
      myRating: 9.9,
      watchStatus: 'completed',
      consumedAt: '2024-01',
      personalReview: 'The most technically accurate portrayal of cybersecurity, Linux terminals, and social engineering in television history, wrapped in a deeply human study of trauma.',
      favoriteCharactersJson: JSON.stringify(['Elliot Alderson', 'Darlene', 'Tyrell Wellick', 'Leon', 'Whiterose']),
      favoriteScenesJson: JSON.stringify(['Season 3 continuous tracking shot episode', 'Season 4 commercial-free heist episode', 'Virtual terminal hack sequences']),
      quotesJson: JSON.stringify(["Hello, friend. Hello, friend? That's lame. Maybe I should give you a name."]),
      tier: 'masterpiece',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'series-silicon-valley',
      slug: 'silicon-valley',
      type: 'tv_series',
      externalProvider: 'tmdb',
      externalId: '60573',
      title: 'Silicon Valley',
      releaseYear: 2014,
      genresJson: JSON.stringify(['Comedy']),
      creatorsJson: JSON.stringify(['Mike Judge']),
      posterUrl: 'https://image.tmdb.org/t/p/w500/wz7VzC1l1zFsmQeQdM6aT0eQ9kK.jpg',
      backdropUrl: null,
      myRating: 9.4,
      watchStatus: 'completed',
      consumedAt: '2023-05',
      personalReview: 'Hilariously perceptive satire of venture capital mania, pivot culture, middle-out compression algorithms, and startup politics.',
      favoriteCharactersJson: JSON.stringify(['Richard Hendricks', 'Jared Dunn', 'Gilfoyle', 'Dinesh', 'Erlich Bachman']),
      favoriteScenesJson: JSON.stringify(['TechCrunch Disrupt presentation', 'Gilfoyle Bitcoin alert siren', 'SWOT analysis board']),
      quotesJson: JSON.stringify(['I am a server architect, not an engineer.', 'Making the world a better place through consensus protocols.']),
      tier: 'favorite',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'series-severance',
      slug: 'severance',
      type: 'tv_series',
      externalProvider: 'tmdb',
      externalId: '95396',
      title: 'Severance',
      releaseYear: 2022,
      genresJson: JSON.stringify(['Sci-Fi', 'Mystery', 'Drama']),
      creatorsJson: JSON.stringify(['Dan Erickson', 'Ben Stiller']),
      posterUrl: 'https://image.tmdb.org/t/p/w500/pPHpeIqlzpTbt12161GgmvmRIm.jpg',
      backdropUrl: null,
      myRating: 9.8,
      watchStatus: 'completed',
      consumedAt: '2023-12',
      personalReview: 'A chilling, surgically crafted dissection of corporate alienation, memory partitioning, and identity. The season finale is textbook cliffhanger perfection.',
      favoriteCharactersJson: JSON.stringify(['Mark Scout', 'Helly R.', 'Irving Bailiff', 'Dylan G.']),
      favoriteScenesJson: JSON.stringify(['The Defiant Jazz dance experience', 'Dylan stretching to hold the Overtime Contingency switches', 'Helly Lumon gala speech']),
      quotesJson: JSON.stringify(['Please try to enjoy each fact equally, and not show preference for any over the others.', 'The work is mysterious and important.']),
      tier: 'masterpiece',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'series-dark',
      slug: 'dark',
      type: 'tv_series',
      externalProvider: 'tmdb',
      externalId: '70523',
      title: 'Dark',
      releaseYear: 2017,
      genresJson: JSON.stringify(['Sci-Fi', 'Mystery', 'Drama']),
      creatorsJson: JSON.stringify(['Baran bo Odar', 'Jantje Friese']),
      posterUrl: 'https://image.tmdb.org/t/p/w500/apbrbWs8M9lyOpJYU5WXrpFbk1Z.jpg',
      backdropUrl: null,
      myRating: 9.7,
      watchStatus: 'completed',
      consumedAt: '2023-03',
      personalReview: 'The absolute pinnacle of deterministic time-travel narratives. Perfectly constructed 33-year cycles, unforgettable score by Ben Frost, and breathtaking symmetry.',
      favoriteCharactersJson: JSON.stringify(['Jonas Kahnwald', 'Claudia Tiedemann', 'Noah', 'Mikkel Nielsen']),
      favoriteScenesJson: JSON.stringify(['Season 1 montage to Familja', 'Claudia explaining the origin world', 'Cave bunker wormhole activation']),
      quotesJson: JSON.stringify(['The question is not where, but when.', 'What we know is a drop, what we don’t know is an ocean.']),
      tier: 'masterpiece',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'series-succession',
      slug: 'succession',
      type: 'tv_series',
      externalProvider: 'tmdb',
      externalId: '76331',
      title: 'Succession',
      releaseYear: 2018,
      genresJson: JSON.stringify(['Drama']),
      creatorsJson: JSON.stringify(['Jesse Armstrong']),
      posterUrl: 'https://image.tmdb.org/t/p/w500/7vjaCdMw15FEbXyLQTVa04URsPm.jpg',
      backdropUrl: null,
      myRating: 9.7,
      watchStatus: 'completed',
      consumedAt: '2023-07',
      personalReview: 'Shakespearean family dynamics colliding with late-stage conglomerate capitalism. Nicholas Britell score and razor-sharp venomous writing.',
      favoriteCharactersJson: JSON.stringify(['Kendall Roy', 'Logan Roy', 'Tom Wambsgans', 'Greg Hirsch', 'Roman Roy']),
      favoriteScenesJson: JSON.stringify(['Season 2 press conference betrayal', 'Connor wedding airplane phone call', 'Meal fit for a king']),
      quotesJson: JSON.stringify(['You are not serious people.', 'I love you, but you are not serious people.']),
      tier: 'masterpiece',
      createdAt: now,
      updatedAt: now,
    },
  ];

  await db
    .insert(schema.mediaEntry)
    .values(mediaEntriesData)
    .onConflictDoUpdate({
      target: schema.mediaEntry.id,
      set: {
        title: sql`excluded.title`,
        posterUrl: sql`excluded.poster_url`,
        myRating: sql`excluded.my_rating`,
        personalReview: sql`excluded.personal_review`,
        favoriteCharactersJson: sql`excluded.favorite_characters_json`,
        favoriteScenesJson: sql`excluded.favorite_scenes_json`,
        quotesJson: sql`excluded.quotes_json`,
        genresJson: sql`excluded.genres_json`,
        creatorsJson: sql`excluded.creators_json`,
        updatedAt: now,
      },
    });

  console.log('✅ Database seeded successfully!');
}

// Auto-run if invoked directly via tsx/node
if (require.main === module) {
  seedDatabase()
    .then(() => process.exit(0))
    .catch((err) => {
      console.error('❌ Seed failed:', err);
      process.exit(1);
    });
}
